### ISSUE TITLE
请问可以教一下doh的写法吗

### ISSUE THREAD

**Issue by gcphym** [chika0801/Xray-examples#1]
想用
https://cloudflare-dns.com/dns-query 远程
https://dns.alidns.com/dns-query 本地
该怎么配置？

https://github.com/XTLS/Xray-core/issues/893

**Comment by chika0801** [comment]
格式参考文档
https://www.v2fly.org/config/dns.html#%E6%94%AF%E6%8C%81%E7%9A%84-dns-%E5%8D%8F%E8%AE%AE%E5%8F%8A%E5%85%B6%E8%B7%AF%E7%94%B1%E7%AD%96%E7%95%A5
