### ISSUE TITLE
您好，按您之前的DNS设置可以屏蔽国内.之后一段时间开全局还是能访问国内网站,示例如下.

### ISSUE THREAD

**Issue by rianjskis** [chika0801/Xray-examples#11]
"dns": {
        "servers": [
            "https://1.1.1.1/dns-query"
          ],
        "queryStrategy": "UseIPv4"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all",
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },

    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ]
}

后来使用您最新的示例中的DNS,还是不能在全局模式中屏蔽国内网站.

**Comment by chika0801** [comment]
猜你是入站里没开域名嗅探参数

你把服务器配置完整发上来看看。你现在发的只有路由部分和出站，所以我也看不到问题。

**Comment by rianjskis** [comment]
{
    "log": {
        "access": "",
        "error": "",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "https://1.1.1.1/dns-query"
          ],
        "queryStrategy": "UseIPv4"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all",
                    "geosite:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": ""
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "",
                        "xver": 1
                        
                     },
                    {
                        "alpn": "h2",
                        "dest": "",
                        "xver": 1
 
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "rejectUnknownSni": true,
                    "minVersion": "1.2",
                    "certificates": [
                        {
                            "certificateFile": "/root/ssl/cert.crt",
                            "keyFile": "/root/ssl/private.key"
                        }
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
        "listen": "0.0.0.0",
        "port": 45577,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": ""
                }
            ]
        },
        "streamSettings": {
            "network": "ws",
            "security": "none",
      "wsSettings": {
          "path": "/ray"
      }
        }
    },
       
        {
            "listen": "127.0.0.1",
            "port": 8006,
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": ""
                    }
                ],
                "fallbacks": [
                    {
                        "dest": "8002",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "sockopt": {
                    "acceptProxyProtocol": true
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ]
}

**Comment by rianjskis** [comment]
> 猜你是入站里没开域名嗅探参数
> 
> 你把服务器配置完整发上来看看。你现在发的只有路由部分和出站，所以我也看不到问题。

看您的新示例中都取消了DNS.跟IPV4设置,这些已经不需要在设置了吗.

**Comment by chika0801** [comment]
> "sniffing": {
>             "enabled": true,
>             "destOverride": [
>                 "http",
>                 "tls"
>             ]
>         }


DNS模块 USE IPv4没写是因为每个人用法一不样，我发模板想了一下，还是少加点自己个性化的内容。不写它们比如不写DNS模块内容，对于VPS就是使用VPS系统默认的DNS。

看了你的配置
你在2个入站都加了域名嗅探参数的。路由模块也是用的IPIfNonMatch，按道理来说，无论客户端发的IP还是域名，VPS收到都按域名处理，用VPS的DNS解析成IP，如果是CN IP就阻止了。

你的配置没有错，你要不再遇到的话，发一下具体的网址。二是你又遇到时，把VPS配置的日志改成debug，然后访问那个网站，你把这时间段的日志帖上来，如果你自己不会看，才能帮你再分析。

**Comment by rianjskis** [comment]
> > “嗅探”：{ 
> > “启用”：是的， 
> > “destOverride”：[ 
> > "http", 
> > “tls” 
> > ] 
> > }
> 
> DNS模块 USE IPv4没写是因为每个人用法一不样，我发模板想了一下，还是少加点自己个性化的内容。不写它们比如不写DNS模块内容，对于VPS就是使用VPS系统默认的DNS。
> 
> 看了你的配置 你在2个入站都加了域名嗅探参数的。路由模块也是用的IPIfNonMatch，按道理来说，无论客户端发的IP还是域名，VPS收到都按域名处理，用VPS的DNS解析成IP，如果是CN IP就阻止了。
> 
> 你的配置没有错，你要不再遇到的话，发一下具体的网址。二是你又遇到时，把VPS配置的日志改成debug，然后访问那个网站，你把这时间段的日志帖上来，如果你自己不会看，才能帮你再分析。

对，之前也是这样的配置.开全局模式访问,知乎,哔哩哔哩,百度贴吧,抖音等网页都是禁止访问的.后来在这里得到新的写法https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165
其他同上不变加入 "domain": "geosite:cn" 后才成功在全局模式下,成功禁止访问cn网页
{
    "log": {
        "access": "/root/xray+nginx/xrayaccess.log",
        "error": "/root/xray+nginx/xrayerror.log",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "https://1.1.1.1/dns-query"
          ],
        "queryStrategy": "UseIPv4"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all",
                    "geosite:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ]
}

**Comment by chika0801** [comment]
看你上一楼的配置也没问题。

你现在，问题解决了吗?是，可关了这ISS了。

**Comment by rianjskis** [comment]
> 看你上一楼的配置也没问题。
> 
> 你现在，问题解决了吗?是，可关了这ISS了。

是的加入后就正常禁止了
