### ISSUE TITLE
Question about nginx_sni_shunting

### ISSUE THREAD

**Issue by Pro100x3mal** [chika0801/Xray-examples#12]
I'm using the VLESS-XTLS-uTLS-REALITY setting. On my vps there are several running sites mydomain.com, www.mydomain.com, site1.mydomain.com, www.site1.mydomain.com, site2.mydomain.com, www.site2.mydomain.com. My site site1.mydomain.com supports TLS v1.3 and h2 - I want to use it as "dest" for "reality". Using the ssl_preread_server_name module I configured all my services to run on port 443:

```
map $ssl_preread_server_name $sni_name {
site1.mydomain.com xray;
mydomain.com site0;
www.mydomain.com site0;
site2.mydomain.com site2;
www.site2.mydomain.com site2;
default def;
}

upstream xray {
server 127.0.0.1:8443;
}

upstream site0 {
server 127.0.0.1:4431;
}

upstream site2 {
server 127.0.0.1:4432;
}

upstream def {
server 127.0.0.1:18443;
}

server {
listen 443 reuseport;
proxy_pass $sni_name;
ssl_preread on;
proxy_protocol on;
}
```

My xray configuration in this case:

```
{
��"log": {
����"loglevel": "info"
��},
��"routing": {
����"rules": [],
����"domainStrategy": "IPIfNonMatch"
��},
��"inbounds": [
����{
������"listen": "127.0.0.1",
������"port": 8443,
������"protocol": "vless",
������"tag": "vless_tls",
������"settings": {
������"clients": [
��������{
����������"id": "xxxxxxxxxxxxx",
����������"email": "ubuntu",
����������"flow": "xtls-rprx-vision"
��������}
������],
������"decryption": "none"
������},
������"streamSettings": {
��������"network": "tcp",
��������"tcpSettings": {
����������"acceptProxyProtocol": true
��������},
��������"security": "reality",
��������"realitySettings": {
����������"show": false,
����������"dest": "127.0.0.1:4430",
����������"xver": 1,
����������"serverNames": [
������������"site1.mydomain.com"
����������],
����������"privateKey": "yyyyyyyyyyyyy",
����������"minClientVer": "",
����������"maxClientVer": "",
����������"maxTimeDiff": 0,
����������"shortIds": [
������������"zzzzzzzzz"
����������]
��������}
����� },
����� "sniffing": {
��������"enabled": true,
��������"destOverride": [
����������"http",
����������"tls",
����������"quic"
��������]
������}
����}
��],
��"outbounds": [
����{
������"protocol": "freedom",
������"tag": "direct"
����},
����{
������"protocol": "blackhole",
������"tag": "block"
����}
��]
}
```

My site, which I use as "dest" for "reality", listens on 127.0.0.1:4430:

```
server {
server_name site1.mydomain.com www.site1.mydomain.com;

listen 127.0.0.1:4430 ssl proxy_protocol;
http2 on;
����ssl_certificate /etc/letsencrypt/live/site1.mydomain.com/fullchain.pem;
����ssl_certificate_key /etc/letsencrypt/live/site1.mydomain.com/privkey.pem;
����include /etc/letsencrypt/options-ssl-nginx.conf;
����ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
…
server {
listen 127.0.0.1:18443 ssl proxy_protocol;

ssl_reject_handshake on;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_timeout 1h;
ssl_session_cache shared:SSL:10m;
ssl_early_data on;
}
…
```

This configuration is fully working. But I'm not sure if I'm using the part correctly that is responsible for default_server with ssl_reject_handshake and listening on 127.0.0.1:18443 with proxy_protocol? This directive in steal_oneself does not contain proxy_protocol, and default_server listens on the same port as the “dest” site itself. Perhaps the best option for me would be to replace the “default def;” block in nginx stream to “default xray” and configure the server block with the ssl_reject_handshake directive to listen to “127.0.0.1:4430 ssl proxy_protocol”?:

```
…
map $ssl_preread_server_name $sni_name {
site1.mydomain.com xray;
mydomain.com site0;
www.mydomain.com site0;
site2.mydomain.com site2;
www.site2.mydomain.com site2;
default def;
…

…
server {
listen 127.0.0.1:4430 ssl proxy_protocol;

ssl_reject_handshake on;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_timeout 1h;
ssl_session_cache shared:SSL:10m;
ssl_early_data on;
…
```

**Comment by TheErf23** [comment]
> mydomain.com

Can you put the complete codes, I can't run it no matter what I do

**Comment by Erfan-Fazeli** [comment]
> من از تنظیم VLESS-XTLS-uTLS-REALITY استفاده می کنم. در vps من چندین سایت در حال اجرا mydomain.com، [www.mydomain.com](http://www.mydomain.com) ، site1.mydomain.com، [www.site1.mydomain.com](http://www.site1.mydomain.com) ، site2.mydomain.com، [www.site2.mydomain.com](http://www.site2.mydomain.com) وجود دارد . سایت من site1.mydomain.com از TLS v1.3 و h2 پشتیبانی می کند - می خواهم از آن به عنوان "dest" برای "واقعیت" استفاده کنم. با استفاده از ماژول ssl_preread_server_name تمام سرویس های خود را برای اجرا در پورت 443 پیکربندی کردم:
> 
> ```
> map $ssl_preread_server_name $sni_name {
> site1.mydomain.com xray;
> mydomain.com site0;
> www.mydomain.com site0;
> site2.mydomain.com site2;
> www.site2.mydomain.com site2;
> default def;
> }
> 
> upstream xray {
> server 127.0.0.1:8443;
> }
> 
> upstream site0 {
> server 127.0.0.1:4431;
> }
> 
> upstream site2 {
> server 127.0.0.1:4432;
> }
> 
> upstream def {
> server 127.0.0.1:18443;
> }
> 
> server {
> listen 443 reuseport;
> proxy_pass $sni_name;
> ssl_preread on;
> proxy_protocol on;
> }
> ```
> 
> پیکربندی xray من در این مورد:
> 
> ```
> {
> ��"log": {
> ����"loglevel": "info"
> ��},
> ��"routing": {
> ����"rules": [],
> ����"domainStrategy": "IPIfNonMatch"
> ��},
> ��"inbounds": [
> ����{
> ������"listen": "127.0.0.1",
> ������"port": 8443,
> ������"protocol": "vless",
> ������"tag": "vless_tls",
> ������"settings": {
> ������"clients": [
> ��������{
> ����������"id": "xxxxxxxxxxxxx",
> ����������"email": "ubuntu",
> ����������"flow": "xtls-rprx-vision"
> ��������}
> ������],
> ������"decryption": "none"
> ������},
> ������"streamSettings": {
> ��������"network": "tcp",
> ��������"tcpSettings": {
> ����������"acceptProxyProtocol": true
> ��������},
> ��������"security": "reality",
> ��������"realitySettings": {
> ����������"show": false,
> ����������"dest": "127.0.0.1:4430",
> ����������"xver": 1,
> ����������"serverNames": [
> ������������"site1.mydomain.com"
> ����������],
> ����������"privateKey": "yyyyyyyyyyyyy",
> ����������"minClientVer": "",
> ����������"maxClientVer": "",
> ����������"maxTimeDiff": 0,
> ����������"shortIds": [
> ������������"zzzzzzzzz"
> ����������]
> ��������}
> ����� },
> ����� "sniffing": {
> ��������"enabled": true,
> ��������"destOverride": [
> ����������"http",
> ����������"tls",
> ����������"quic"
> ��������]
> ������}
> ����}
> ��],
> ��"outbounds": [
> ����{
> ������"protocol": "freedom",
> ������"tag": "direct"
> ����},
> ����{
> ������"protocol": "blackhole",
> ������"tag": "block"
> ����}
> ��]
> }
> ```
> 
> سایت من، که من از آن به عنوان "بهترین" برای "واقعیت" استفاده می کنم، در 127.0.0.1:4430 گوش می دهد:
> 
> ```
> server {
> server_name site1.mydomain.com www.site1.mydomain.com;
> 
> listen 127.0.0.1:4430 ssl proxy_protocol;
> http2 on;
> ����ssl_certificate /etc/letsencrypt/live/site1.mydomain.com/fullchain.pem;
> ����ssl_certificate_key /etc/letsencrypt/live/site1.mydomain.com/privkey.pem;
> ����include /etc/letsencrypt/options-ssl-nginx.conf;
> ����ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
> …
> server {
> listen 127.0.0.1:18443 ssl proxy_protocol;
> 
> ssl_reject_handshake on;
> 
> ssl_protocols TLSv1.2 TLSv1.3;
> ssl_session_timeout 1h;
> ssl_session_cache shared:SSL:10m;
> ssl_early_data on;
> }
> …
> ```
> 
> این پیکربندی به طور کامل کار می کند. اما مطمئن نیستم که از بخشی که مسئول default_server با ssl_reject_handshake و گوش دادن به 127.0.0.1:18443 با پروکسی_پروتکل است، به درستی استفاده می کنم؟ این دستورالعمل در steal_oneself حاوی proxy_protocol نیست و default_server در همان پورت خود سایت "dest" گوش می دهد. شاید بهترین گزینه برای من جایگزینی "default def" باشد. در nginx استریم را به «xray پیش‌فرض» مسدود کنید و بلوک سرور را با دستور ssl_reject_handshake برای گوش دادن به «127.0.0.1:4430 ssl proxy_protocol» پیکربندی کنید؟:
> 
> ```
> …
> map $ssl_preread_server_name $sni_name {
> site1.mydomain.com xray;
> mydomain.com site0;
> www.mydomain.com site0;
> site2.mydomain.com site2;
> www.site2.mydomain.com site2;
> default def;
> …
> 
> …
> server {
> listen 127.0.0.1:4430 ssl proxy_protocol;
> 
> ssl_reject_handshake on;
> 
> ssl_protocols TLSv1.2 TLSv1.3;
> ssl_session_timeout 1h;
> ssl_session_cache shared:SSL:10m;
> ssl_early_data on;
> …
> ```

Can you put the complete codes, I can't run it no matter what I do

**Comment by chika0801** [comment]
I'm sorry, I don't have the time or energy to help you.
