### ISSUE TITLE
你好 按照你的trojan-tls-tcp配合nginx节点是通的 但是nginx不能用，请指点指点 谢谢

### ISSUE THREAD

**Issue by kabu0124** [chika0801/Xray-examples#12]
root@s7551 ~ # cat /etc/nginx/nginx.conf 
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format main '[$time_local] $proxy_protocol_addr "$http_user_agent"';
    access_log /var/log/nginx/access.log main;
    set_real_ip_from 127.0.0.1;
    real_ip_header proxy_protocol;
    server {
        listen 127.0.0.1:10012 proxy_protocol;
        listen 127.0.0.1:10024 http2 proxy_protocol;
        set_real_ip_from 127.0.0.1;
        server_name abc.asd.com.me;
        proxy_ssl_server_name on;

            location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5212;
    }
  }
}

**Comment by chika0801** [comment]
location / {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_host;
proxy_redirect off;
proxy_pass http://127.0.0.1:5212;
}


你要传给 5212端口的，我不知道这样写对不对，你自行搜索了，我没搞再深入学这块。


建议别用这些了，迟早端口被封，回落功能也不要用了，要不上vision要不用hysteria这类。

**Comment by kabu0124** [comment]
好的 谢谢
