### ISSUE TITLE
Hi I want to ask about VLESS-TCP-XTLS-Vision configuration. Does config need to install caddy/nginx? If yes please guide me. I sincerely thank

### ISSUE THREAD

**Issue by Thaomtam** [chika0801/Xray-examples#13]

**Comment by chika0801** [comment]
caddy/nginx 可以不用安装。

**Comment by Thaomtam** [comment]
> caddy/nginx 可以不用安装。

I installed caddy from official website. Once installed, it signs the certificate itself. And I can't find where the certificate is located. To add in xray config. Can you help help. Idol

**Comment by chika0801** [comment]
我不使用Caddy，我不知道Caddy生成的ssl证书的目录是什么。你需要自己搜索一下结果。

**Comment by Thaomtam** [comment]
> 我不使用Caddy，我不知道Caddy生成的ssl证书的目录是什么。你需要自己搜索一下结果。
> 
> https://blog.csdn.net/thinszx/article/details/127002586

Thank you. I watched it too. But not found. I have tested on ProxySU and it shows that it lets the caddy listen to the self-signed certificate (acme). But I don't know how to do it. According to your rating caddy vs nginx

**Comment by Thaomtam** [comment]
> 我不使用Caddy，我不知道Caddy生成的ssl证书的目录是什么。你需要自己搜索一下结果。
> 
> https://blog.csdn.net/thinszx/article/details/127002586

Thank you. I watched it too. But not found. I have tested on ProxySU and it shows that it lets the caddy listen to the self-signed certificate (acme). But I don't know how to do it. According to your rating caddy vs nginx

**Comment by chika0801** [comment]
我使用 https://github.com/acmesh-official 申请免费的SSL证书

或者你去 https://www.ssls.com/ 购买 5年时间约20美元。

一份SSL证书，你可以在多个VPS上面使用，不需要把域名解析到VPS的IP。

在客户端GUI，填写你的代理节点信息时，我是把地址填写成VPS的IP，SNI填写成有效证书里，包含的域名。

这是我的使用习惯。

**Comment by ArcCal** [comment]
默认设置（不手动指定证书签发机构）的情况下，证书保存在这里：
/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/

**Comment by Thaomtam** [comment]
> 默认设置（不手动指定证书签发机构）的情况下，证书保存在这里：
> /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/

Thank god. You are my savior. I have found what I need. Can you suggest me the h1-2-3 caddy configuration as well. Thank you
