### ISSUE TITLE
Reverse proxy XTLS-VISION

### ISSUE THREAD

**Issue by vahidx4r4x** [chika0801/Xray-examples#14]
Hi,
thanks for your great effort.
2 Questions:
1. Is it possible to hide xtls-vision behind the nginx and a camo website? kinda like wulabing's vless-tls-ws nginx front.
2. Is it possible to make it work behind the CloudFlare' CDN?

TNX

**Comment by chika0801** [comment]
1 Is it possible to hide xtls-vision behind the nginx and a camo website? kinda like wulabing's vless-tls-ws nginx front.

vision不能，只能xray监听端口，使用tcp传输协议。

2 Is it possible to make it work behind the CloudFlare' CDN?

不能。不支持使用CDN。
