### ISSUE TITLE
wireguard warp config

### ISSUE THREAD

**Issue by hawshemi** [chika0801/Xray-examples#15]
let's say I have this outbound on my server:

```
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "wireguard",
            "settings": {
                "MTU": 1280,
                "DNS": "1.1.1.1 1.0.0.1",
                "secretKey": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
                "address": [
                    "172.16.0.2/32",
                    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                ],
                "peers": [
                    {
                        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "allowedIPs": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "endpoint": "engage.cloudflareclient.com:2408"
                    }
                ]
            },
            "tag": "WARP"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
```
Can I change the Cloudflare IP server? because there is a list of CF Warp servers that it will connect to the nearest server. So when I set up with Germany VPS, it will connect to Germany Warp IP address. Can I connect to the USA WARP server manually?

**Comment by chise0713** [comment]
Cloudfalre WARP's IP is based on your IP address, basicly, if you use a USA IP to connect, you will get a WARP's USA IP, you can not manually chose your WARP IP address.

**Comment by hawshemi** [comment]
@chise0713 But some scripts can change warp IP region like https://gitlab.com/fscarmen/warp. for example: `warp i hk`.

**Comment by chise0713** [comment]
That won't work, or that us a reverse proxy IP as endpoint.

**Comment by hawshemi** [comment]
So there is no way that I can change the WARP region?
even with other scripts or warp services or wireguard cores or .... ?

**Comment by chise0713** [comment]
You can search for reverse proxies, it is the only way to change your WARP IP region.

**Comment by hawshemi** [comment]
Can you elaborate on that?

**Comment by chise0713** [comment]
Sorry, can't help you with that. Usually reverse proxy it is against the TOS, you can buy another vps to reverse proxy it by yourself.

**Comment by chika0801** [comment]
> So there is no way that I can change the WARP region? even with other scripts or warp services or wireguard cores or .... ?

I also think that, for example, your VPS is German, and the Warp information you get accesses the German warp IP. you can't make the warp IP change to a US warp IP on a German VPS. if there's a way to do it, with the Xray profile method that I know of, I've tried and failed at it as well. As for something like the fscarmen/warp script to change the WarpIP of the region where the VPS is located. i've only seen the script for it before, i don't use this feature and don't understand the way it's implemented.

I would suggest that you can buy a US VPS and make your US VPS set up with a good warp configuration.

For example you can go from your region ---> to the German VPS ---> to the US VPS, and the outbound of the US VPS is into warp.

**Comment by hawshemi** [comment]
I know. I have a USA VPS and WARP installed on it. some services and rules from our Germany VPS will go through the USA VPS & USA WARP.
I wanted to delete the USA VPS and connect to USA WARP directly...
