### ISSUE TITLE
请问怎么使用vless+vision+reality成功上网？

### ISSUE THREAD

**Issue by tztnuaji** [chika0801/Xray-examples#16]
首先介绍一下现状：
1.我购买了一台新的vps，在vps上我分别clone了xray-core，xray-install，xray-examples

2.安装xray成功后，我编辑了xray-examples/vless+vision+reality/config_server.json，主要修改了这几个地方：
domainStrategy更改为Asls，
dest更改为www.google.com:443，
privateKey更改为运行xray x25519得到的，
shortIds同样，除此以外没做其他修改

3.将修改后的文件，复制到/usr/local/etc/xray/config.json

4.systemctl start xray && exit

5.我确信客户端也是完全按照配置文件上要求去填写的，但是连接失败了，手机端v2rayNG则显示net/http: TLS handshake timeout

请问我应该怎么做才能成功使用？是少了什么步骤吗？

**Comment by chika0801** [comment]
说下我的流程

1. 买1台VPS，使用网络重装系统脚本，安装成Debian12。（你可以根据自己的情况，省略这一步）
2. 使用 `bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta` 安装Xray 1.8.6
3. 复制服务端配置 https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/config_server.json 到 /usr/local/etc/xray/config.json ，不修改里面的内容，使用`systemctl restart xray`重启Xray
4. https://github.com/chika0801/Xray-examples/tree/main/VLESS-Vision-REALITY 参数这里客户端GUI程序的填写内容，这里给的客户端配置内容和它的服务端配置内容REALITY相关参数，是一套组合。比如v2rayN。在v2rayN中添加好它，并使用v2rayN自动设置系统代理。使用电脑浏览器访问，测试能否打开google.com。
5. 如果有需要，再参考配置示例，修改REALITY相关参数。
6. 电脑端成功，再尝试在v2rayNG上添加。

看了你写的信息，我阅读后，我不能有效的帮助到你。

**Comment by tztnuaji** [comment]
好的，谢谢你的认真回复
