### ISSUE TITLE
您好请问VLESS-TCP-XTLS-Vision

### ISSUE THREAD

**Issue by rianjskis** [chika0801/Xray-examples#16]
有带warp国内出站得配置写法吗,另如果带warp出站,nginx还需要做改动吗,谢谢,

**Comment by chika0801** [comment]
warp 国内出站？

一般是用在VPS端，把CN IP的丢进Warp。你问的是这个意思吗？

不是再说下具体的？

Warp的配置文件，官方文档，更新说明也有提。

**Comment by rianjskis** [comment]
> warp 国内出站？
> 
> 一般是用在VPS端，把CN IP的丢进Warp。你问的是这个意思吗？
 
> 不是再说下具体的？
> 
> Warp的配置文件，官方文档，更新说明也有提。

是的. 听说geosit的CN IP走warp,比直接黑洞安全一点.就想着用您这个配置在加上warp国内出站到warp

**Comment by chika0801** [comment]
1 有新洛杉矶 大部分香港的VPS IP 用不了wgcf注册的warp，这时只能用Warp-go。

建议你先用https://github.com/fscarmen/warp 里面有wgcf和warp-go2个版本的一键，你先测试Wgcf能通。然后建议重装系统或卸载后再从Xray开始

2 wgcf注册见 https://github.com/XTLS/Xray-core/issues/1385#issuecomment-1328540742

3 xray配置文件写法见 https://github.com/XTLS/Xray-core/issues/1385#issuecomment-1329621046

至于分流geoip cn文档有示例吧。
