### ISSUE TITLE
While attempting to compile Xray per your instructions, I see this issue.Failed to stop xray.service: Unit xray.service not loaded.

### ISSUE THREAD

**Issue by us254** [chika0801/Xray-examples#17]
sudo systemctl stop xray

Failed to stop xray.service: Unit xray.service not loaded.

 1:  curl -sLo go.tar.gz https://go.dev/dl/go1.20.1.linux-amd64.tar.gz: This downloads the Go programming language version 1.20.1 for Linux x86-64 and saves it as a compressed tarball named go.tar.gz.

 2:  tar -C /usr/local -xzf go.tar.gz: This extracts the contents of the go.tar.gz archive into the /usr/local directory.

 3:  rm go.tar.gz: This deletes the go.tar.gz file.

 4:  export PATH=$PATH:/usr/local/go/bin: This adds the go binary directory to the system path so that it can be executed from anywhere.

 5:  go version: This checks the installed version of Go to confirm that it was successfully installed.

 6:  apt install -y git: This installs the Git version control system.

 7:  git clone https://github.com/XTLS/Xray-core.git: This clones the Xray-core repository from GitHub.

 8:  cd Xray-core: This changes the current working directory to the newly cloned Xray-core repository.

 9:  go mod download: This downloads all the Go module dependencies required by Xray-core.

10:  CGO_ENABLED=0 go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main: This builds the Xray-core binary named xray in the current directory using Go. It also sets some flags to optimize the binary and reduce its size.

11:  systemctl stop xray: This stops the Xray-core service if it is currently running.

12:  cp xray /usr/local/bin: This copies the newly compiled xray binary to the /usr/local/bin directory, where it can be executed from anywhere.

13:  systemctl start xray: This starts the Xray-core service.

14:  cd ..: This changes the current working directory back to the parent directory.

15:  rm -rf go Xray-core: This deletes the go directory and the Xray-core repository directory, which are no longer needed.

**Comment by chika0801** [comment]
你可以先使用：

 `bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta `

安装 xray。

systemctl stop xray 它就可以工作了。

**Comment by us254** [comment]
> You can first use:
> 
> `bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta `
> 
> Install xray.
> 
> systemctl stop xray and it works.



sudo systemctl stop xray
sudo rm /usr/local/bin/xray
git clone https://github.com/XTLS/Xray-core.git
cd Xray-core
go mod download
go build -o xray ./main
sudo cp xray /usr/local/bin
sudo nano /etc/systemd/system/xray.service


In the editor that opens, paste the following configuration:
---------------------
[Unit]
Description=Xray-core Service
After=network.target

[Service]
ExecStart=/usr/local/bin/xray -config /etc/xray/config.json
Restart=on-failure

[Install]
WantedBy=multi-user.target
--------------------
Save the file and exit the editor.




sudo systemctl daemon-reload
sudo systemctl enable xray
sudo systemctl start xray

**Comment by us254** [comment]
Before receiving your response, I tried to address my problem using these commands.

**Comment by chika0801** [comment]
> Before receiving your response, I tried to address my problem using these commands.

我认为，大家都使用了 `bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta ` 安了 xray-core。 所以不会遇到你的情况。
