### ISSUE TITLE
重载Nginx报错

### ISSUE THREAD

**Issue by Wyatt323** [chika0801/Xray-examples#19]
Dec 25 12:52:32 VM-730MWW9UN9N7 systemd[1]: Starting A high performance web server and a reverse proxy server...
Dec 25 12:52:32 VM-730MWW9UN9N7 nginx[18291]: nginx: [emerg] unknown directive "ssl_reject_handshake" in /etc/nginx/nginx.conf:40
Dec 25 12:52:32 VM-730MWW9UN9N7 nginx[18291]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 25 12:52:32 VM-730MWW9UN9N7 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Dec 25 12:52:32 VM-730MWW9UN9N7 systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 25 12:52:32 VM-730MWW9UN9N7 systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by chika0801** [comment]
`unknown directive "ssl_reject_handshake" in /etc/nginx/nginx.conf:40`

有可能是你的NGINX版本太老了。

我平时是用 https://nginx.org/en/linux_packages.html 里面官方的安装命令安的。

这链接中有一行运行版本，你可以试试。

https://github.com/chika0801/Xray-install

**Comment by Wyatt323** [comment]
根据您的提示，已经不会报错了，但是发现无法反代成功，同时节点也不通

**Comment by Wyatt323** [comment]
![image](https://github.com/chika0801/Xray-examples/assets/71224625/78e1f765-bc9a-4e02-8e97-7cb5f3705933)

**Comment by chika0801** [comment]
我也不能帮你了，这种问题，问不到网友，就只能靠自己研究。

另外建议你问时，基本的要把配置发出来这种提问技术要有。
