### ISSUE TITLE
What is `reserved` in `wireguard` ?

### ISSUE THREAD

**Issue by hawshemi** [chika0801/Xray-examples#2]
In the [Wireguard](https://github.com/chika0801/Xray-examples/blob/main/wireguard.md) section, what is the `"reserved":[0, 0, 0]` parameter? 
I use https://github.com/ViRb3/wgcf but it doesn't generate any `reserved` numbers.

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/wireguard.md

There is this value after registering using the method in this link.

It is generally used on Hong Kong vps, and some Los Angeles vps, which use WARP on vps in these areas, to add this value or the connection won't work.

**Comment by hawshemi** [comment]
Do you know what is the meaning of it?
I didn't enter anything and the warp is working ok. so it's not needed?

**Comment by chika0801** [comment]
The 3 values are standardized by cloudflare itself I believe, probably no one has looked into what it means.

If you don't add them on your vps, you can use warp, and it's fine if you don't add them. They are only used on vps with Hong Kong, some LA ip's as I said above.

**Comment by hawshemi** [comment]
Thanks.
