### ISSUE TITLE
how to make multi password on this config ?

### ISSUE THREAD

**Issue by scriptvpskita** [chika0801/Xray-examples#2]

**Comment by scriptvpskita** [comment]
shadowsocks tcp :)

**Comment by chika0801** [comment]
"inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 50001,
            "protocol": "shadowsocks",
            "settings": {
                "clients": [
                    {
                        "password": "example_user_1",
                        "method": "aes-256-gcm"
                    },
                    {
                        "password": "example_user_2",
                        "method": "aes-256-gcm"
                    }
                ],
                "network": "tcp,udp",
                "ivCheck": true
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none"
            }
        }
    ],

from here https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-AEAD

**Comment by chika0801** [comment]
one port more user.
