### ISSUE TITLE
use "generatewarpplusbot" to get warp+

### ISSUE THREAD

**Issue by mortezaafshar92** [chika0801/Xray-examples#20]
HI
i use "generatewarpplusbot" to get warp plus, bu i don't know what to put in this section 👉  "reserved":[0, 0, 0], // 粘贴你的 "reserved" 值

**Comment by chika0801** [comment]
This value is useful if your vps is Hong Kong, or Los Angeles part of the ip address , you must add them to connect to the warp.
They are obtained using the tool mentioned in my article.

**Comment by chika0801** [comment]
If you're not experiencing problems with not being able to connect to warp, this parameter is not used and has no effect.
