### ISSUE TITLE
The 443 port of my VPS using vless-vision-reality got blocked.

### ISSUE THREAD

**Issue by MaplerK** [chika0801/Xray-examples#22]
I have set up a node using vless-vision-reality primarily for gaming purposes. The method of usage involves enabling the Tun mode in v2rayN. The VPS provider is saltyfishtech, and the server is located in San Jose, US West. I chose the official website of a school in San Jose as the sni. I am using port 443, but it got blocked today. Could you please help me check if there is any issue with my client and server configurations?
```
{
  "log": {
    "loglevel": "warning"
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "type": "field",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ]
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ],
    "domainStrategy": "IPIfNonMatch"
  },
  "dns": null,
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "streamSettings": null,
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": null,
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "iVyj.love@xray.com",
            "flow": "xtls-rprx-vision",
            "id": "5457f8b5-95bb-4981-ec5c-f6c81e7aa0d2"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      },
      "streamSettings": {
        "network": "tcp",
        "realitySettings": {
          "dest": "siliconvalley.basisindependent.com:443",
          "maxClient": "",
          "maxTimediff": 0,
          "minClient": "",
          "privateKey": "4PMof7xujGR3csDkfba9uh0sPR1UDUlH8OllBbJWbUk",
          "serverNames": [
            "siliconvalley.basisindependent.com"
          ],
          "shortIds": [
            "",
            "cf",
            "1916",
            "f78c89",
            "c9145850"
          ],
          "show": false,
          "xver": 0
        },
        "security": "reality",
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "inbound-443",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "transport": null,
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "reverse": null,
  "fakeDns": null
}
```
![Screenshot 2024-01-05 031100](https://github.com/chika0801/Xray-examples/assets/50393047/dcc41c30-7abe-4e09-811b-5549065ad0a2)

**Comment by chika0801** [comment]
Checked what you have filled out on the server side and the client side and it is fine.

Why port 443, is blocked by the government firewall in your area, I don't know why.

You do not love the VPS port and IP, it is recommended to change the 443 to other ports to continue to use, if you meet again when the connection fails, they will change the port on the line.

**Comment by MaplerK** [comment]
> Checked what you have filled out on the server side and the client side and it is fine.
> 
> Why port 443, is blocked by the government firewall in your area, I don't know why.
> 
> You do not love the VPS port and IP, it is recommended to change the 443 to other ports to continue to use, if you meet again when the connection fails, they will change the port on the line.

感謝您的耐心檢查與回復。補充一下落地isp為kirino。
一些問題：443端口會被封禁是不是就説明了僞裝度不足？參照其他issue的説法，reality改用非443端口的僞裝度會更差，對嗎？
可能的原因會是針對該學校域名的流量過多嗎？使用該節點接近一周，從v2rayN上看，total download traffic 是10GB+，但從xui上看僅不到3GB。
通過ping該學校的域名，為San Fransisco的cloudflare汎播，不是San Jose，這是否也影響了僞裝度。
采用學校節點的原因是，參考了XTLS/Xray-core#2005中的做法篩選出來的同段ip的域名基本為中文内容，於是參考了XTLS/Xray-core/discussions/2256中的建議，選擇了您推薦的節點附近的學校域名。

**Comment by chika0801** [comment]
你不会担心你发送数据的内容会被怎么样。

防火墙它怎么封到你这vps443的，防火墙那边是黑盒也不可能知道具体原因。

只要不是被封ip，因为被封ip要么花钱换ip，买其它机，给你造成不方便。

所以我说遇到不通会查，会改端口继续用就是了。

要交流的话，我自己用偷自己形式的一些机还没遇到被封443的情况
