### ISSUE TITLE
照抄ng出错了巨佬

### ISSUE THREAD

**Issue by Axe-l** [chika0801/Xray-examples#22]
照抄ng出错了巨佬，[](url)
<img width="467" alt="image" src="https://user-images.githubusercontent.com/45731066/222966583-d8516674-fd5d-4924-88f6-fb1839a9e4e6.png">
![776](https://user-images.githubusercontent.com/45731066/222966623-7cc06436-6b06-4fc6-806d-1fb72e4cc153.jpg)

**Comment by chika0801** [comment]
发这图没用。你要说清楚你用的哪个模板，最好帖你的配置，然后说你是电脑上用N手机NG都不行，还是比如N行NG不行

建议搜下提问的智慧，这样别人才能更好帮到你。
