### ISSUE TITLE
fault when apply ssl with standalone mode

### ISSUE THREAD

**Issue by alonewoo** [chika0801/Xray-examples#23]
It is fault when apply ssl with standalone mode and port 80 is free. Error log is as below:
 www.sample.tk:Verify error:2a01:4f8::::1: Fetching http://www.sample.tk/.well-known/acme-challenge/4HXM4gRV4sC2qQwKsMNWgzf6_08CzaQz1xiAgs8C79A: Connection refused
[Mon 06 Mar 2023 06:39:46 PM CET] Please add '--debug' or '--log' to check more details.
[Mon 06 Mar 2023 06:39:46 PM CET] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

But it is ok when I apply the ssl with :
acme.sh --issue -d www.sample.tk --webroot /var/www/html/ --keylength ec-256  --force .

The server is pure ipv6 in Hax.id.

I know it may not is the issue of the sample configuration. I just want to get some help..............

**Comment by chika0801** [comment]
对不起，你的问题，我也不明白，我帮不了你。

你可以使用一台IPv4的VPS申请SSL证书。申请到的这份SSL证书你可以在其它的VPS上使用，只要证书还在有效期以内。

在客户端GUI界面，地址处填写其它VPS的IP，SNI处填写申请这个证书时候用的域名，就可以了。

方便你测试，在多台VPS之间使用。

希望上面的建议对你有作用。

**Comment by chika0801** [comment]
我自己是去 https://www.ssls.com/ 购买的SSL证书 5年时间大约是20美元。
