### ISSUE TITLE
PR_END_OF_FILE_ERROR: Unable to visit websites within China using VLESS-Vision-REALITY

### ISSUE THREAD

**Issue by R8s6** [chika0801/Xray-examples#24]
Using[ VLESS-Vision-REALITY](https://github.com/chika0801/Xray-examples/tree/main/VLESS-Vision-REALITY), I had no problem connecting to any websites OUTSIDE GFW.

But, Firefox / Safari / iOS apps are unable to connect to Chinese websites (within GFW) such as baidu.com, jd.com, or taobao.com.

Firefox error code:
```
An error occurred during a connection to jd.com. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

What could be wrong?

Thanks a lot!

**Comment by chika0801** [comment]
```json
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block" // del
            }
        ]
```
Remove this rule , it means that the request (domain name) you receive with the VPS DNS query if it is a CN IP, block outbound.

**Comment by R8s6** [comment]
Thank you very much! It solved the issue.
