### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY: steal_yourself，访问域名时提示unsafe site.

### ISSUE THREAD

**Issue by JoviDong** [chika0801/Xray-examples#24]
首先感谢大佬，VLESS-XTLS-uTLS-REALITY steal_yourself 已经可以正常使用了。本人不会编程，在这提个笨问题，在配置完成后当天不使用工具直接访问域名（证书中包含的域名）会正常显示nginx指向的网站music.youtube.com（现在指向的是www.cloudflare.com），但是第二天再次访问时提示unsafe site，在pc上的chrome, edge, firefox浏览器访问都是同样的提示，手机端safari, chrome, edge, firefox 正常访问无提示。xray 能正常使用，这个问题对我来说也没什么影响，因为我不做网站。

![pc-chrome-unsafe-site](https://user-images.githubusercontent.com/39184341/223608510-51e5083e-593a-41a7-9606-d9e363d0fde5.png)
![pc-edge-unsafe-site](https://user-images.githubusercontent.com/39184341/223608593-e1d77277-5a7e-4019-b2cf-75fc47ed648b.png)
![pc-firefox-unsafe-site](https://user-images.githubusercontent.com/39184341/223608624-d79d081a-7edf-461a-89ba-de49061831e8.png)

另外再提个问题，在现有的配置方案 VLESS-XTLS-uTLS-REALITY steal_yourself 基础上，如果想要国内用户访问域名时提示 "该服务在该地区不可用"，有可能实现吗？
![service unavailable](https://user-images.githubusercontent.com/39184341/223609365-6e1765ad-72b5-4a42-9661-4c8de93a4fad.png)

最后，感谢大佬的付出。

**Comment by chika0801** [comment]
> 另外再提个问题，在现有的配置方案 VLESS-XTLS-uTLS-REALITY steal_yourself 基础上，如果想要国内用户访问域名时提示 "该服务在该地区不可用"，有可能实现吗？

我还去搜索（不会）想了下，应该是要在nginx配置里，改真实用户访问请求，是nginx接的。至于nginx怎么改配置，我也没搜索过，不会了。

**Comment by chika0801** [comment]
你把nginx里反代的网址，换成其它的保存重启nginx，再测试下有不有这种提示了。我反代的那个动漫网站倒是一切正常。

反代的nginx配置是来自 https://www.digitalocean.com/community/tools/nginx?global.app.lang=zhCN 挺好用的生成网站

**Comment by chika0801** [comment]
比如你用我默认那个动漫网址，修改后保存nginx配置，重启nginx生效后，你去浏览器输你的域名，应该能正常显示动漫网站的内容吧？

如果不行，就奇怪了。

**Comment by chika0801** [comment]
反正反代的网站，也不会有人看，我是个人爱好填的那个网址。

**Comment by chika0801** [comment]
自己偷自己目的主要是把服务端的TLS那指纹，换成了nginx的（nginx处理SSL证书）
xray的是go语言的指纹。

**Comment by chika0801** [comment]
你意思是你反代用我那个网址，也是这种提示吗？如果是，我也没遇到过，不懂为什么。

**Comment by chika0801** [comment]
> > 你意思是你反代用我那个网址，也是这种提示吗？如果是，我也没遇到过，不懂为什么。
> 
> 是的，反代过你用的那个网址，也是一样。后来换了很多支持TLS1.3和H2的网址，也是一样。

这我也不知道你出现的原因了
