### ISSUE TITLE
用了vision的nginx配置文件，为什么没有办法启动，一直报错

### ISSUE THREAD

**Issue by vicdorke** [chika0801/Xray-examples#25]
nginx.service is not active, cannot reload.

**Comment by chika0801** [comment]
我是用nginx http://nginx.org/en/linux_packages.html 官网命令安的，是正常的，你为什么出错，我不知道了

apt install -y gnupg2 ca-certificates lsb-release debian-archive-keyring && curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor > /usr/share/keyrings/nginx-archive-keyring.gpg && echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/debian `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list && echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" > /etc/apt/preferences.d/99nginx && apt update -y && apt install -y nginx && mkdir -p /etc/systemd/system/nginx.service.d && echo -e "[Service]\nExecStartPost=/bin/sleep 0.1" > /etc/systemd/system/nginx.service.d/override.conf && systemctl daemon-reload

**Comment by vicdorke** [comment]
好了，似乎是nginx编码的错

**Comment by chika0801** [comment]
好的
