### ISSUE TITLE
MUX - gRPC+TLS 

### ISSUE THREAD

**Issue by hawshemi** [chika0801/Xray-examples#26]
Hello. 
I the table below:
<img width="701" alt="image" src="https://github.com/chika0801/Xray-examples/assets/16742123/80230f40-93b0-4a5c-8c80-c6c55f419539">

It is said that **Vless+gRPC+TLS** (with Nginx) comes with **MUX**.

1. What is the default number of mux?
2. There is no need to set mux from the client in this config? or do I have to set mux? _(like below)_

```
            "mux": {
                "enabled": true,
                "concurrency": 8, 
                "xudpConcurrency": 8, 
                "xudpProxyUDP443": "reject"
            }
```

**Comment by chika0801** [comment]
> What is the default number of mux?

I'm also not sure what the default MUX is for gRPC.

> There is no need to set mux from the client in this config? or do I have to set mux? (like below)

```
            "mux": {
                "enabled": true,
                "concurrency": -1,  
                "xudpConcurrency": 8, 
                "xudpProxyUDP443": "reject"
            }
```

"concurrency": -1,  

The gRPC MUX conflicts with Xray's built-in TCP MUX, which you can turn off like this. But you can use the new UDP MUX feature in XUDP. This new feature is not necessary, you can try it, it is UDP over TCP, it will not conflict with gRPC's MUX.

**Comment by hawshemi** [comment]
So when the transport is `gRPC`, mux is automatically enabled and used by the client and server?

**Comment by chika0801** [comment]
> So when the transport is `gRPC`, mux is automatically enabled and used by the client and server?

yes This is a fundamental feature of gRPC (HTTP2).

**Comment by hawshemi** [comment]
Thanks. Appreciate it.
