### ISSUE TITLE
VLESS-XTLS+H2+gRPC-uTLS-REALITY/steal_yourself 能实现吗

### ISSUE THREAD

**Issue by JoviDong** [chika0801/Xray-examples#26]
自己尝试配置了 VLESS-XTLS+H2+gRPC-uTLS-REALITY，应该是能使用，暂时未遇到什么问题。

想请教下大佬，VLESS-XTLS+H2+gRPC-uTLS-REALITY/steal_yourself 能实现吗。

感谢。

**Comment by chika0801** [comment]
> 想请教下大佬，VLESS-XTLS+H2+gRPC-uTLS-REALITY/steal_yourself 能实现吗。

可以吧，我也没写配置测试，觉得没什么必要。h2/grpc没什么区别，现在来看就clash meta核心的客户端只能用grpc。
