### ISSUE TITLE
使用Reality时，fallback和dest优先级的问题

### ISSUE THREAD

**Issue by YaphetS911** [chika0801/Xray-examples#28]
我看到这份配置中，同时使用了settings中的fallbacks和realitySettings中的dest，这两个配置是否存在优先级的关系？

https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-REALITY/config_server_shared_port.json

**Comment by chika0801** [comment]
不存在，你客户端中填的是 VLESS-Vision-REALITY 还是 VLESS-gRPC-REALITY 都行。服务端是个2选1的意思。

你问个优先级没懂你表达的什么。你客户端出站又不能同时填2种。客户端出站你只能用1种形式。

**Comment by YaphetS911** [comment]
我理解的回落是指协议不匹配时路由到哪里去，fallbacks和dest都起到了回落的功能，所以如果一个非reality的请求，会回落到grpc去还是dest指向的www.lovelive-anime.jp:443去呢？

**Comment by YaphetS911** [comment]
> 不存在，你客户端中填的是 VLESS-Vision-REALITY 还是 VLESS-gRPC-REALITY 都行。服务端是个2选1的意思。
> 
> 你问个优先级没懂你表达的什么。你客户端出站又不能同时填2种。客户端出站你只能用1种形式。

@chika0801 
我理解的回落是指协议不匹配时路由到哪里去，fallbacks和dest都起到了回落的功能，所以如果一个非reality的请求，会回落到grpc去还是dest指向的www.lovelive-anime.jp:443去呢？

**Comment by chika0801** [comment]
> 所以如果一个非reality的请求，会回落到grpc去还是dest指向的www.lovelive-anime.jp:443去呢

dest处填的网址那儿处，原理是REALITY的工作流程。
