### ISSUE TITLE
`* 7 * * *`这个cron不太好吧

### ISSUE THREAD

**Issue by 70599** [chika0801/Xray-examples#3]
这里写成`* 7 * * *`的话，应该是7点的每分钟都运行（运行60次？）吧？
https://github.com/chika0801/Xray-examples/blob/2ae7d324de6136785528561b4a6d04cefe83405c/VMess-QUIC-TLS/README.md?plain=1%23L45

**Comment by chika0801** [comment]
感谢你，发现这问题了。
