### ISSUE TITLE
Wireguard inbound 

### ISSUE THREAD

**Issue by M03ED** [chika0801/Xray-examples#31]
Hi.
In the beginning I want to thank you for your excellent repo , I use your samples a lot.
As a request can you add wireguard inbound sample to repo ?

**Comment by chika0801** [comment]
https://sing-box.sagernet.org/configuration/inbound/

In sing-box, there is no support for the wireguard protocol in the inbound category.

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/pull/2477

Refer to this link, I haven't tried it myself.
