### ISSUE TITLE
nginx_sni_shunting: for client what public key should be enetered?

### ISSUE THREAD

**Issue by zerodwide** [chika0801/Xray-examples#35]
Dear @chika0801 
Thanks for your great examples.

I am following your guide nginx_sni_shunting in 
https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/nginx_sni_shunting/

private key in config_server.json is empty
the client is connecting to nginx at first, and using .key file in nginx config

so what public key should be used for client?

is there any tool to convert private key file .key generated by acme to public key string and entering that exact public key for client?

note:
i want to use my own domain and my own ssl on nginx

**Comment by chika0801** [comment]
> so what public key should be used for client?

https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/nginx_sni_shunting/config_server.json#L68

This parameter is used when using REALITY, you can check the information about REALITY and generate it.

They have nothing to do with stealing your own mode in your NGINX configuration, the real SSL certificate that NGINX is going to load.

> i want to use my own domain and my own ssl on nginx

You use this configuration, and the SSL certificate is also something you have to prepare yourself. Whether you use ACME to apply for a free certificate, or purchase a paid certificate yourself.

**Comment by zerodwide** [comment]
Thanks for response.

when we are using NGINX in front of REALITY, still we need to generate privateKey in config_server.json and fill publicKey for client?

Reality Client -> NGINX (+Real SSL) -> REALITY server

**Comment by chika0801** [comment]
> when we are using NGINX in front of REALITY, still we need to generate privateKey in config_server.json and fill publicKey for client?

privateKey  publicKey 

These 2 parameters are mandatory when using REALITY, so you should definitely configure them yourself if you use REALITY.

NGINX front listening to 443, SNI shunt to different ports on your VPS, as the back, not necessarily must use REALITY to steal their own form, NGINX in the front of the external listening, is a separate part. What to use in the back, you can also choose your own other protocol methods to match.

Translated with DeepL.com (free version)

**Comment by zerodwide** [comment]
Thanks dear @chika0801
