### ISSUE TITLE
关于使用XTLS-VISION和XTLS-REALITY网速慢的疑问

### ISSUE THREAD

**Issue by Iyiren** [chika0801/Xray-examples#35]
VPS系统Ubuntu18.04，按照教程分别安装了XTLS-VISION和XTLS-REALITY后，观看YouTube视频，查看网络连接信息，VISION的链接速度是8000多kbps，而REALITY只有3000多kbps。以前用TLS-TCP-WS，可以达到几万kbps。VPS是美西cera的。ping延迟180~200ms，VPS带宽60Mbps。

**Comment by chika0801** [comment]
这种看YTB时，速度差异是什么原因我也分析不出来 。我自己用的VPS，都是对我好回程线路，我没有观察到用不同组合（VISION+TLS，或VISION+REALITY）有差异。

对我来说我看YTB4K我观察速度的话一般都10W+（搬瓦工美西4837回程），一个HK CMI回程一般是20W+
