### ISSUE TITLE
请问reality偷自己的客户端正确配置是什么？

### ISSUE THREAD

**Issue by Pacio** [chika0801/Xray-examples#36]
![image](https://user-images.githubusercontent.com/6836705/227928116-54e867b0-e4ff-4a0d-8755-2bec18d2dc59.png)
需要修改图中哪些选项呢

**Comment by chika0801** [comment]
我的习惯是

地址填vps的ip

域名填你上传到vps的ssl证书中包含的域名（这域名可不用指向vps的ip或指向了也无所谓）

其它内容你看config里面的注释，有不懂的现场问就是了。
