### ISSUE TITLE
请增加VLESS-H2-uTLS-REALITY的clash.meta格式样本

### ISSUE THREAD

**Issue by yjps** [chika0801/Xray-examples#37]
如题，请增加VLESS-H2-uTLS-REALITY的clash.meta格式样例
在 https://github.com/chika0801/Xray-examples/blob/main/Clash_Meta_For_Android.yaml 并没有找到样例

**Comment by chika0801** [comment]
meta的h2没修，能用，但是不快，所以没加，你可去meta的tg君咨询。
