### ISSUE TITLE
VLESS-gRPC-REALITY is possible along side with nginx_sni_shunting?

### ISSUE THREAD

**Issue by zerodwide** [chika0801/Xray-examples#37]
Is it possible to implement VLESS-gRPC-REALITY in nginx_sni_shunting?
i tried with xray gRPC server config but it failed.

I dont know how to modify nginx config to make grpc works!

it would be great if TCP+GRPC works together, if not, GRPC alone is ok. 

Thanks in Advance.

**Comment by chika0801** [comment]
It's possible, although I haven't tested it myself. I think the point of attention is the NGINX configuration in the SNI shunt, fill in the domain name and your XRAY configuration in the DEST parameter that domain name should be the same, SNI shunt function can be properly transferred to your VPS corresponding listening port.

The main purpose of SNI diversion is to share port 443. In fact, I don't use SNI shunt myself, my VPS just do proxy, the simpler the more convenient principle.

Translated with DeepL.com (free version)
