### ISSUE TITLE
客户端配置inbounds中建议加上sniffing

### ISSUE THREAD

**Issue by winds365** [chika0801/Xray-examples#38]
https://xtls.github.io/config/inbound.html#inboundobject
如果没有sniffing，则routing中的端口分流，network:tcp,udp分流，域名分流不起作用

**Comment by chika0801** [comment]
因为这些客户端配置，比如 https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-TLS/config_client.json

环境都是使用win系统代理，此时就是http或socks代理的模式。这种模式下，发到xray侧的请求类型都会是域名。

推荐一个远古文章，但是初学入门推荐 https://tachyondevel.medium.com/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0

所以示例中入站部分，写不写嗅探的参数，都行，写了也等于不会发生效果。

**Comment by winds365** [comment]
域名分流这个应该写不写都一样
但是端口分流真的不启做用
我说下我的环境
Netch拦截游戏进程转发给本地socks代理
如果不加sniffing
这样的规则不启做用，全部走的直连
`      {
        "type": "field",
        "port": "443",
        "network": "tcp",
        "outboundTag": "proxy"
      }
      {
        "type": "field",
        "port": "23301",
        "network": "udp",
        "outboundTag": "proxy",
        "ip": [
          "47.245.0.0/18",
          "8.209.192.0/18"
        ]
      },
`

**Comment by chika0801** [comment]
我也没用过Netch。我是sing-box开TUN，DNS和路由部分，由sing-box处理，xray只用来连服务端，这用法。

你有兴趣的话，可看这连接 https://github.com/chika0801/sing-box-examples/tree/main/Tun/self-use
