### ISSUE TITLE
错误排查

### ISSUE THREAD

**Issue by kukuci** [chika0801/Xray-examples#4]

**Comment by chika0801** [comment]
同一个规则之内，各个依据需要同时成立，才会匹配成功，逻辑关系是 和，而不是 或。
{
"type": "field",
"ip": [
"geoip:cn",
"geoip:private"
],
"outboundTag": "block"
}
这里同时写了两个规则，要同时满足这两个条件基本不可能。所以你这条无效。

虽然你编辑掉了。我收到邮件了。。。

建议你看下文档自己再自学一下。。。
