### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by Wyatt323** [chika0801/Xray-examples#40]
https://github.com/chika0801/Xray-examples/commit/ff2e1c00cd1a45dd010f5a4ceb8158591906b364
上述修改后启动出现下面的错误
![image](https://user-images.githubusercontent.com/71224625/229353161-4f2532e5-5787-42c5-878a-7cfc9be9ce9a.png)
换成换来的127.0.0.1就没问题，不知道这部分用127和您修改后的有什么差别吗

**Comment by Wyatt323** [comment]
好像这个nginx反代失效了？我nginx运行成功，但是刷不出页面

**Comment by chika0801** [comment]
2种传递方式没什么区别啦。

我改下127的传统的好了。。。

**Comment by Wyatt323** [comment]
我刚才找了两台机器重新搭建的，这个nginx配置文件好像不起作用了，反代了打不开页面
