### ISSUE TITLE
"dest" 里 是一个跳转能行？

### ISSUE THREAD

**Issue by toyo2333** [chika0801/Xray-examples#40]
域名是xyz.com 打开后 是跳转 : https://www.xyz.com/site/en/home

配置了能用。

但想知道这样用有没有什么问题。

**Comment by toyo2333** [comment]
另外 我用了caddy，偷自己的时候 如果 “ "xver": 1, // 发送 PROXY protocol” 这里设置为1反而不行，设置为0 才成功 咋回事

**Comment by chika0801** [comment]
虽然我不用CADDY。如果你  "xver": 1 不通，表示CADDY配置中不支持（或你没正确配置） PROXY protocol，所以XRAY配置这边，你设置为0才通。0就0吧，效果应该是NGINX看不到网站访问者的IP，也没什么影响。

**Comment by chika0801** [comment]
> 域名是xyz.com 打开后 是跳转 : https://www.xyz.com/site/en/home
> 
> 配置了能用。
> 
> 但想知道这样用有没有什么问题。

没明白你想问的是什么意思

**Comment by toyo2333** [comment]
> > 域名是xyz.com 打开后 是跳转 : https://www.xyz.com/site/en/home
> > 配置了能用。
> > 但想知道这样用有没有什么问题。
> 
> 没明白你想问的是什么意思

没什么问题了。我改为偷自己了。偷自己目前就上面那个xver的问题。我研究研究。

我找找 
        set_real_ip_from           127.0.0.1;
        real_ip_header             proxy_protocol;
 这这个对应的caddy配置

**Comment by toyo2333** [comment]
> 虽然我不用CADDY。如果你 "xver": 1 不通，表示CADDY配置中不支持（或你没正确配置） PROXY protocol，所以XRAY配置这边，你设置为0才通。0就0吧，效果应该是NGINX看不到网站访问者的IP，也没什么影响。

确实是配置的问题。解决了。
