### ISSUE TITLE
VLESS-H2-uTLS-REALITY 方案是否支持 fallbacks

### ISSUE THREAD

**Issue by lvii** [chika0801/Xray-examples#41]
Hi

参考 https://github.com/chika0801/Xray-examples/blob/main/VLESS-H2-uTLS-REALITY/config_server.json

增加 `fallbacks` 没有回落到 nginx 请求 ：

                "fallbacks": [
                    {
                        "dest": "8004",
                        "xver": 1
                    }
                ]

之前使用 [VLESS-XTLS-Vision](https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-Vision) 非 REALITY 是正常的

感谢

**Comment by chika0801** [comment]
我也没试过再加回落，我看官方配置示例说明，就只搞了这个最简单即是好的原则，的这个示例。

你再回落是想的n个协议共用1端口这想法吗？

**Comment by roachsinai** [comment]
> 不用的，等REALTY文档出来会解释的吧。我理解的意思是探测的那些流量都转发到你DEST目标网站去了

那如果是偷自己呢？

**Comment by chika0801** [comment]
偷自己时，服务端的 serverNames 我一直是填的我本机由NGINX加载的那SSL证书中包含的域名，这域名指向了本机IP。

你也可填任何域名，客户端保持一致也能通。有什么不好的地方我也不知道。

**Comment by chika0801** [comment]
> 一个疑问是之前看网上配置 vless 的教程都说 gfw 会进行探测，所以需要配置一个 fallback。

这是 REALITY出来前的时代，用交流用语 VLESS+Vison流控+TCP+TLS 形式，Xray这边一直觉得有必要配一个回落，到本机如nginx。当然也有不同的观点如不配回落的。

用REALITY不用配 fallback 这参数。

偷自己的话反正刚出REALITY时大家讨论了就这样在用的，用了几个月了，没什么其它要折腾的了。
