### ISSUE TITLE
配置文件交流~

### ISSUE THREAD

**Issue by 1trapcode** [chika0801/Xray-examples#42]
首先 感谢分享配置
吴彦祖为你点赞👍
### 目前参考的是偷自己证书
path: steal_yourself/nginx.conf
31-34行
```
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
```

如果不想占用本地80端口可以修改成域名
```
    server {
        listen 域名:80;
        return 301 https://$host$request_uri;
    }
```

然后我遇到了了问题
前提: 以确认编译好对应的模块
nginx/1.23.4
`sudo tail -f /opt/nginx/logs/xray/access.log`
没有看见 `$time_local` 和 `$proxy_protocol_addr`

我是抄了作者这份作业.
猜测是不是应该也把`access_log`放置到server块中?

**Comment by chika0801** [comment]
你遇到的问题是 access_log 日志中少了什么内容吗？

**Comment by chika0801** [comment]
$time_local 为什么没有，我想不到原因。

$proxy_protocol_addr 没访问都的IP是因为不用 $proxy_protocol_addr 这个参数。因为别人访问你是 域名:80，这个形式，不是通过XRAY传递到nginx，在nginx里用了 proxy_protocol;，对应用 $proxy_protocol_addr 。

域名:80 形式对应日志里要有IP的那个参数是 $remote_addr

你试试。

**Comment by chika0801** [comment]
好的
