### ISSUE TITLE
reality可以配置fallback吗？

### ISSUE THREAD

**Issue by HuengchI** [chika0801/Xray-examples#43]
reality可以配置fallback吗？fallback必须偷自己吗？可以偷别人吗？

**Comment by HuengchI** [comment]
是的，我想把网站和扶梯建在一个机器上节省成本。但是reality比较令人困惑，它什么时候会触发fallback呢？如果想访问网站，应该访问什么网址呢？

**Comment by chika0801** [comment]
所以我建议你别省一个vps的钱了，建站和翻墙用不同vps，你也不差这点钱，何必给自己找东西学了。这看法。
