### ISSUE TITLE
xray-core 1.8版的 VLESS-H2-uTLS-REALITY 的 TLS in TLS

### ISSUE THREAD

**Issue by xgmq** [chika0801/Xray-examples#44]
请问新版xray-core 1.8版的VLESS有padding修复TLS in TLS特征吗？

我想要跑VLESS-H2-uTLS-REALITY，浏览网页比较滑顺。但怕曝露TLS in TLS特征。

**Comment by chika0801** [comment]
h2  grpc 都有 tls in tls，但是你参考这里的说明 https://github.com/chika0801/Xray-examples/blob/main/warning.md#memo-3

不要爱惜VPS的端口即可放心用好了
