### ISSUE TITLE
certificates in steal_yourself configuration

### ISSUE THREAD

**Issue by aleskxyz** [chika0801/Xray-examples#45]
Hi,
I'm trying to use steal_youself configuration.
Regarding to certificate:
https://github.com/chika0801/Xray-examples/blob/f9133a5e542cb91931427054bb5a25e3779d0d87/VLESS-XTLS-uTLS-REALITY/steal_yourself/nginx.conf#L40
Do I need to generate a self-signed certificate for it?
Or I have to get a valid certificate for my own domain and use my domain in reality configuration?
Regards

**Comment by chika0801** [comment]
我没有试过用自签名证书能不能工作。

我认为REALITY这个技术，不应该用自己签名的证书。

自己偷自己的证书，也要求自己的SSL证书是真正的。
