### ISSUE TITLE
VLESS-XHTTP-REALITY/steal_oneself中server端设置问题

### ISSUE THREAD

**Issue by yasuis** [chika0801/Xray-examples#46]
用大佬给的方案outbound不工作，把sniffing段放上面就正常了 请大佬测试
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "@xhttp",
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "clients": [
                    {
                        "id": "chika"
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "xhttpSettings": {
                    "path": "/lovelive"
                }
            },
            **"sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }**
        },
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "@xhttp"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "target": "8001",
                    "xver": 1, // 发送 PROXY protocol
                    "serverNames": [
                        "example.com", // 与 Nginx 配置中的 server_name 一致
                        "chika.example.com"
                    ],
                    "privateKey": "",
                    "shortIds": [
                        ""
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}

**Comment by chika0801** [comment]
我想了一下，是应该这样改一下更好。
