### ISSUE TITLE
configuration_plus_points 里“目标网站”是指？

### ISSUE THREAD

**Issue by Toad-stool** [chika0801/Xray-examples#47]
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 目标网站的IP:80
iptables -t nat -A PREROUTING -i eth0 -p udp --dport 443 -j DNAT --to-destination 目标网站的IP:443
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

这一步骤中的“目标网站”是指？
先谢。

**Comment by chika0801** [comment]
"dest": "www.lovelive-anime.jp:443",

你在VPS上PING这域名得到的IP

**Comment by Toad-stool** [comment]
> "dest": "www.lovelive-anime.jp:443",
> 
> 你在VPS上PING这域名得到的IP

你好。
我大概明白了，但我按照 configuration_plus_points 设置完之后，

访问 VPS的 IP:80 （国内直连），显示：

403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

访问 VPS的 IP:443 （国内直连），显示：

400 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

我理解的是
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 目标网站的IP:80
iptables -t nat -A PREROUTING -i eth0 -p udp --dport 443 -j DNAT --to-destination 目标网站的IP:443
这两条命令将 访问VPS的流量转发至www.lovelive-anime.jp？不知道我的理解对吗，上面的400、403报错是否意味着我设置失败？
感谢。

**Comment by chika0801** [comment]
那文件的意思是 https://github.com/XTLS/REALITY

这里面有一句话

配置加分项：禁回国流量，TCP/80、UDP/443 也转发（REALITY 对外表现即为端口转发，目标 IP 冷门或许更好）

其实加不加也无所谓。

至于你用的访问VPS：443 显示 什么

你要测试 REALITY效果，我们是这样的，把windows的hosts文件，VPS的IP 对应你目标网站域名，保存。

然后关，开浏览器，输入目标网站网址，显示的是那网站的内容。

**Comment by Toad-stool** [comment]
> 那文件的意思是 https://github.com/XTLS/REALITY
> 
> 这里面有一句话
> 
> 配置加分项：禁回国流量，TCP/80、UDP/443 也转发（REALITY 对外表现即为端口转发，目标 IP 冷门或许更好）
> 
> 其实加不加也无所谓。
> 
> 至于你用的访问VPS：443 显示 什么
> 
> 你要测试 REALITY效果，我们是这样的，把windows的hosts文件，VPS的IP 对应你目标网站域名，保存。
> 
> 然后关，开浏览器，输入目标网站网址，显示的是那网站的内容。

通过本地hosts文件的方式测试成功，看来是正确配置了转发，感谢感谢。
