### ISSUE TITLE
希望增加 nginx SNI stream TCP 分流复用 443 端口的配置示例

### ISSUE THREAD

**Issue by lvii** [chika0801/Xray-examples#48]
Hi

希望增加一个 nginx SNI stream TCP 分流复用 443 端口的实例

感谢！

**Comment by chika0801** [comment]
不好意思，我的观点是简单就是最好的，NGINX前置 SNI分流的配置建议你搜下有博客文章样。我水平不够不能简明写出文章来我就放弃了。我自己也不用这么复杂的N合一配置。所以我就没加（不想花精力什么都学懂，只学自己想要用到的）是这样。
