### ISSUE TITLE
请教wireguard模板里可以用ipv6分流吗

### ISSUE THREAD

**Issue by jaesony** [chika0801/Xray-examples#49]
将AllowedIPs的0.0.0.0/0改为::/0连不上

**Comment by chika0801** [comment]
你如果想能不能V6优先，https://github.com/XTLS/Xray-core/issues/1385#issuecomment-1330049744 我在这个ISS里当时就测过，没成功。

所以放的示例教程上都没写V6相关的。如果非要用，换我，我是用全局接管流量的形式（无论用一键脚本，还是我习惯手动安）大约是这样的解决方法。以上我是个人的习惯

**Comment by jaesony** [comment]
我把172.16.0.2换成warp里的ipv6地址，好像能用，用bgp.he.net检测到的也是cloudflare的ipv6。用ipv6主要是为了解锁netflix，racknerd洛杉矶的vps获取warp一直只有一个ipv4地址，无法解锁，现在用ipv6可以了

**Comment by chika0801** [comment]
> 我把172.16.0.2换成warp里的ipv6地址，好像能用，用bgp.he.net检测到的也是cloudflare的ipv6。用ipv6主要是为了解锁netflix，racknerd洛杉矶的vps获取warp一直只有一个ipv4地址，无法解锁，现在用ipv6可以了

是这样的
