### ISSUE TITLE
注册warp后无法导出wireguard配置

### ISSUE THREAD

**Issue by yasuis** [chika0801/Xray-examples#52]
参照wireguard.md中命令在debian11下运行没有任何反应，无任何提示，请大佬看一下，谢谢

**Comment by chika0801** [comment]
warp-go注册warp账户出错了，已经有几天了。

你可先试试  https://github.com/badafans/warp-reg 这个，我还没试

**Comment by chika0801** [comment]
curl -sLo warp-reg https://github.com/badafans/warp-reg/releases/download/v1.0/main-linux-amd64 && chmod +x warp-reg && ./warp-reg

用它吧

**Comment by kdurov** [comment]
不想用第三方的 warp 工具，毕竟有自己的 team token。
官方的 warp-cli 的话，配置在`/var/lib/private/cloudflare-warp` 里（自己写的 service，配置了 dynamicuser 所以可能和出厂的配置路径略有不同，应该是不在 /private 底下）

里面有三个文件 `conf.json, reg.json` 和 `settings.json`，大致看下
`routing_id ` 应该就是对应 reserved，要转换成 hex 的样子。
`reg.json` 里面的 `secret_key` 应该就是自己的 private key。

不过问题是有两个 public key

1.  `conf.json` 有 `own_public_key` 和 `public_key` 两个 keys，其中 `own_public_key` 和 `reg.json` 里面的 `public_key` 是一样的。用 wg pubkey 计算  `secret_key`  对应的公钥是这个值。
2. `conf.json` 里面的  `public_key`  和 wgc f以及网上随便找到的 warp 公钥是一样的都是`"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="`

不知道有没哪位试过 zero trust team 情况下是不是可以无视 `"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="` 这个。还是说这个另有用途？
