### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY中steal_yourself steal_yourself的nginx.conf配置问题

### ISSUE THREAD

**Issue by yasuis** [chika0801/Xray-examples#59]
nginx.conf第60行 set $website     www.lovelive-anime.jp;
这里的网站应该填自己的还是lovelive-anime或者填什么都行，请教一下

**Comment by chika0801** [comment]
这是你要反代的网址，你可以换成你自己的其它网址，但是不同网址显示出来反代成功多少要你自己测试。

**Comment by chika0801** [comment]
你不管这网址也行，GFW又不会人工输入你的域名看有什么网页内容。只是个人无聊做的事罢了。我觉得你放个NINGX默认网页都行。
