### ISSUE TITLE
v2rayNG开启fakedns时，inbound "tag": "dns-in"的设置问题

### ISSUE THREAD

**Issue by gcphym** [chika0801/Xray-examples#6]
参考配置 https://github.com/chika0801/Xray-examples/blob/main/Shadowsocks-2022-TCP/config_client_v2rayNG_custom.json
```json
{
            "listen": "127.0.0.1",
            "port": 10853,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "1.1.1.1",
                "port": 53,
                "network": "tcp,udp"
            },
            "tag": "dns-in"
}
```
请问 既然配置了fakedns 后面的"address"为什么要配置成"1.1.1.1" 乱填一个"0.0.0.3"好像也可以正常使用

**Comment by gcphym** [comment]
在这里找到了答案 https://guide.v2fly.org/basics/dns.html#%E5%AF%B9%E5%A4%96%E5%BC%80%E6%94%BE-v2ray-%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1
”...而DNS出站协议会拦截Type A和Type AAAA的 DNS 查询并交由 v2ray 内置 DNS 处理，从而返回查询结果；除此之外的查询流量，会根据Dokodemo的配置发送至目标 DNS 服务器。“
但还是好奇”非Type A和Type AAAA的 DNS 查询“有哪些？

**Comment by chika0801** [comment]
> 在这里找到了答案 https://guide.v2fly.org/basics/dns.html#%E5%AF%B9%E5%A4%96%E5%BC%80%E6%94%BE-v2ray-%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1 ”...而DNS出站协议会拦截Type A和Type AAAA的 DNS 查询并交由 v2ray 内置 DNS 处理，从而返回查询结果；除此之外的查询流量，会根据Dokodemo的配置发送至目标 DNS 服务器。“ 但还是好奇”非Type A和Type AAAA的 DNS 查询“有哪些？

原理我在这学的

https://guide.v2fly.org/basics/dns.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

然而，这样配置存在一定问题。对于非Type A和Type AAAA的 DNS 查询，v2ray 将会直连转发至dns-in中所设置的目标 DNS 服务器。而当这个域名被污染时，返回的自然是被污染的结果；如果希望 v2ray 内置 DNS 承担 DNSCrypt-Proxy 的作用，这样无疑会导致 DNS 查询内容的泄露。

解决方法有两种：

在dns-out中，添加proxySettings的配置，使得非Type A和Type AAAA的 DNS 查询经由remote-proxy-out转发至远端解析。此时，目标为8.8.8.8:53的非Type A和Type AAAA的 DNS 查询流量通过代理转发至远端，并通过远端 v2ray 的freedom出站，发往8.8.8.8:53从而返回未经污染的结果。

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS

最下面的推荐文章那些，我当时看完想了好久，慢慢懂了
