### ISSUE TITLE
配置VLESS-TCP-Vision-REALITY后用浏览器访问自己IP显示“已拒绝连接”

### ISSUE THREAD

**Issue by JackChong2008** [chika0801/Xray-examples#6]
Hi Chika,
感谢提供配置模板。我照搬了你最基础的REALITY配置（就是lovelive-anime.jp的哪一款），可以科学上网。但是当浏览器输入自己VPS的IP后，显示“已拒绝连接”（ERR_CONNECTION_REFUSED），不显示lovelive-anime.jp的站点内容。这样似乎不能伪装自己的VPS。请问这是正常现象吗？

**Comment by chika0801** [comment]
测试方法：设你是win11，改hosts文件，内容是 vps的ip 空格 和servername（应该没记错）

保存hosts文件，然后重新打开浏览器，输入https://vpsip 你试试能正常显示lovelive-anime.jp不了

**Comment by JackChong2008** [comment]
Hi Chika,
感谢提供测试方法。
我是win10，已根据你的方法修改hosts文件，加入条目：**.***.***.**  www.lovelive-anime.jp。
浏览输入IP，依然显示“已拒绝连接”（ERR_CONNECTION_REFUSED）。若强制手打https://IP，则显示“此站点的连接不安全”；“使用不受支持的协议”。
win10系统是否还需要其他的设置？

**Comment by chika0801** [comment]
给你说错了，（太久记不清了）去测试了，测试方法是浏览器输入 [www.lovelive-anime.jp](http://www.lovelive-anime.jp./) 能显示网页内容，则为正常。（不是上面给你说的输入https://vpsip

因为你改了hosts。你可以在cmd窗口ping [www.lovelive-anime.jp](http://www.lovelive-anime.jp./) 就是你VPS的IP

所以你关，开浏览器，输入[www.lovelive-anime.jp](http://www.lovelive-anime.jp./) 因为系统hotst实际是访问你自己的VPS的，所以这样验证。

**Comment by JackChong2008** [comment]
Hi Chika,
感谢指导。本地ping www.lovelive-anime.jp和浏览其访问该地址显示网站内容的测试都已通过。
请容许我多问一句：如果GFW用浏览器访问我VPS的IP的方法主动探测我的VPS，我的VPS依然不会显示该站点内容，其实还是会被怀疑。对吗？

**Comment by chika0801** [comment]
> 如果GFW用浏览器访问我VPS的IP的方法主动探测我的VPS，我的VPS依然不会显示该站点内容，其实还是会被怀疑。对吗？

你意思是GFW用https://IP 形式访问，好多正常网站也阻止了这种形式。这种形式，别人扫得到你的SSL证书。

**Comment by chika0801** [comment]
比如 https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-Vision/config_server.json#L47 这个参数就是干阻止的事

nginx中也有对应 参数 https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC/nginx.conf#L41

**Comment by JackChong2008** [comment]
明白了，谢谢你！
