### ISSUE TITLE
希望能出一个xtls+vision+udp443的配置模板

### ISSUE THREAD

**Issue by 9779779** [chika0801/Xray-examples#62]
希望能出一个xtls+vision+udp443的配置模板，谢谢

**Comment by chika0801** [comment]
如果不需要用REALITY的话，你参考 https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-Vision/config_client_simple.json 这里面的，其实只用把 "flow": "xtls-rprx-vision" 选（改）成 "flow": "xtls-rprx-vision-udp443"

注意，通常这样用时，比如你在WIN系统，需要透明代理环境（代理UDP）（比如用sing-box开TUN模式）

参考 https://github.com/chika0801/Xray-install/tree/main/Tun

**Comment by chika0801** [comment]
你如果不懂透明代理环境 TUN模式 之类的区别，建议你不要在意代理QUIC流量。

**Comment by 9779779** [comment]
好的，谢谢
