### ISSUE TITLE
[求助]Warp代理协议Socks出站不能走IPv6访问站点

### ISSUE THREAD

**Issue by toyo2333** [chika0801/Xray-examples#63]
---我看了你的例子，但它不适用proxy模式实现的。

我说说的情况：

我是双栈机器，原本vps就可以访问ChatGTP，浏览器打开 https://chat.openai.com/cdn-cgi/trace 里可以看到IP使用了VPS自己的IPv6地址。

我的目的也很简单就是：再套一层warp（用Warp-cli set-mode proxy的socks代理模式，只想用这个模式）， 最终让浏览器以warp的IPv6访问ChatGTP。

配置下来后：

1，在VPS上用curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000 确认VPS默认优先使用了warp的IPv6访问了chatgpt，没问题

2，但我电脑用浏览器访问，但是却显示用了Warp的IPv4地址（还是通过上面的地址查看）。

我想了下，我浏览器应该没问题，因为原本就可以IPv6访问，VPS也没问题，因为上述命令行也是通过代理转发，所以也不是代理模式的问题。那就只能是Xray的问题了？实在搞不懂哪里出了问题，我的配置是这样的，改动的很少：

路由规则如下，增加了分流路由：

```
   {
        "type": "field",
        "outboundTag": "warp",
        "domain": [
			"openai.com",
			"ai.com",
			"chat.openai.com.cdn.cloudflare.net",
			"openaiapi-site.azureedge.net",
			"ip.sb"
        ]
      },
```

出站代理和网上的教程一样设置转发到socks协议的40000端口，发现只能走warp的IPv4后，我试了下面两种指定"UseIPv6"的设置都不行，无效！！

设置1：增加"streamSettings"，在底层sockopt设置策略

```
    {
      "tag": "warp",
      "protocol": "socks",
      "streamSettings": {
	  "sockopt": {"domainStrategy": "UseIPv6"}
	  },
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },

```
设置2：直接在settings里增加策略
```

	{
      "tag": "warp",
      "protocol": "socks",
      "settings": {
	   "domainStrategy": "UseIPv6"
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },
```
恳请 分析下哪里有问题，该如何实现我的需求（**在用proxy模式的前提下**）？

盼望回复，谢谢！

**Comment by chika0801** [comment]
不好意思。我帮不上了。

因为我没有在VPS上用过官方Warp cli程序开socks端口。然后xray配置中出站把你要的域名转到warp的socks端口，这种形式。

所以我不知道要实现你的只想走v6，以现在xray配置中，用比如你尝试的 设置1 设置2 的方式你都失败了。我不用，所以我也没花时间去研究过。

我想到一个方案你参考下。

如果你放弃必须用官方Warp cli监听sokcs端口形式，有以下建议：

方法1，用sing-box https://github.com/chika0801/sing-box-examples/blob/main/wireguard.md 这方法试过是能实现V6

方法2，用一键warp或手动安装，只全局接管VPS出站的V6流量，这要配置比如Xray配置中出站UseIPv6能实现一样的目的。

**Comment by chika0801** [comment]
Warp-cli set-mode proxy的socks代理模式

这模式我从没用过，只是听说用久了爆你VPS的内存。不清楚你为什么执着于官方cli程序，我看xray群里的人用的也不多。

**Comment by toyo2333** [comment]
原因有3个：

1，warp-cli这个是从官方网站下载并按其文档指令操作的，wireguard这种我不懂，但看上去是第三方的，而且有很多人做脚本，我都不知道那些脚本安不安全。不敢去curl。

2，这Proxy模式设置比较简单，不需要什么Key啊，改配置，set-mode，然后connect后就生效了，简单。

3，我用warp-cli默认的warp模式那个导致过vps失联断网，只能重装vps的系统。。你看看这篇文章的最后那一部分：https://lala.im/8225.html，我不知道第三方的这些有没有类似的大坑。

我是希望尽可能的保持系统的“干净”（内容方法都来自官方自己）

谢谢你的回答，我再去了解研究下你的这个wireguard，我到现在都没搞懂他们的区别。

**Comment by chika0801** [comment]
> 1，warp-cli这个是从官方网站下载并按其文档指令操作的，wireguard这种我不懂，但看上去是第三方的，而且有很多人做脚本，我都不知道那些脚本安不安全。不敢去curl。

https://github.com/fscarmen/warp 这个挺有名的，其它人用好久了，没见什么黑历史。

>3，我用warp-cli默认的warp模式那个导致过vps失联断网，只能重装vps的系统。。你看看这篇文章的最后那一部分：https://lala.im/8225.html

>> 如果不使用warp客户端的本地代理模式，直接代理服务器全部流量的话肯定会导致服务器无法连接。

当Warp全局接管流量，你怎么用SSH连接上你的VPS，这在比如 https://github.com/fscarmen/warp 这脚本作者就考虑好了有解决方法。你以兴趣可以看脚本代码研究。不是问题。

**Comment by toyo2333** [comment]
> 方法2

解决了，谢谢，用的方法2，使用了wgcf一键安装配置

**Comment by chika0801** [comment]
所以你当时为什么执着于官方warp cli客户端哈哈哈

**Comment by toyo2333** [comment]
> 所以你当时为什么执着于官方warp cli客户端哈哈哈

当时觉得灵活，简单。只设置一个特别出口，有需要的域名才丢过去。

**Comment by toyo2333** [comment]
> 所以你当时为什么执着于官方warp cli客户端哈哈哈

内存占用确实大，虽然不会持续泄露，但至少有50MB

**Comment by toyo2333** [comment]
还有个问题就是。设置的时候配置文件那个MTU值是脚本自动测算生成的。这个值的修改，会影响我的网络性能么？不被接管的ipv4栈会收影响么？

**Comment by chika0801** [comment]
> 还有个问题就是。设置的时候配置文件那个MTU值是脚本自动测算生成的。这个值的修改，会影响我的网络性能么？不被接管的ipv4栈会收影响么？

你如果手动用wgcf生成配置，我记得默认是1280，我没对比这个改成1400和1280有什么区别。

比如你用那些一键我记得流程中有一个项目是帮你自动计算，我当时试的时候给的值是141X样。

这点MTU差异影响不了太多性能 内核 wireguard跑进warp你VPSCPU不是问题的话最大就约700Mbps左右了。
