### ISSUE TITLE
关于wireguard.md

### ISSUE THREAD

**Issue by KoinuDayo** [chika0801/Xray-examples#65]
现在xray的域名策略似乎[是prefer而不是v*only](https://github.com/XTLS/Xray-core/pull/2014#issuecomment-1532296454)，所以在[wireguard.md](https://github.com/chika0801/Xray-examples/blob/main/wireguard.md)中两个 `freedom` 出站似乎只需要一个 ` "domainStrategy": "UseIPv6" ` 就行？即使不是prefer那它也是在 `UseIPv6` 之后没拿到 `IPv6` 而[走 `AsIs` ](https://github.com/XTLS/Xray-core/pull/2014#issuecomment-1532419844)。

只是提了下自己的看法，很有可能有错误，希望能指出。

**Comment by chika0801** [comment]
那个pr还没合，合了后会改，目前只能这样写
