### ISSUE TITLE
wireguard里api.zeroteam.top作用是什么

### ISSUE THREAD

**Issue by jaesony** [chika0801/Xray-examples#66]
warp-reg输出的账号信息和api.zeroteam.top输出的有什么区别

**Comment by chika0801** [comment]
> warp-reg输出的账号信息和api.zeroteam.top输出的有什么区别

没有区别。昨天正好看 https://github.com/fscarmen/warp ，最下面 服务提供（排名不分先后）:

CloudFlare Warp(+): https://1.1.1.1/
WGCF 项目原作者: https://github.com/ViRb3/wgcf/
Coia 和 warp-go 团队: https://gitlab.com/ProjectWARP/warp-go
warp-go api wiki: https://docs.zeroteam.top/apis/warp

这里提到 warp-go api wiki: https://docs.zeroteam.top/apis/warp，之前用War-go能直接注册现在被封，结果换成这个API了，这API写的是获取。warp-reg主页写的是注册。就这2个区别吧。
