### ISSUE TITLE
v2rayNG_custom_fakedns.json导入json的情况下，是否还要在客户端设置中勾选启用虚拟DNS

### ISSUE THREAD

**Issue by Ra1nhom** [chika0801/Xray-examples#69]
RT

**Comment by chika0801** [comment]
不用，勾了也没用。

那选项的作用是你使用ng填节点信息，它帮你生成配置，生不生成fakedns的内多都全自定义了，xray core读的就是你自己自定义的东西

**Comment by KoinuDayo** [comment]
> 不用，勾了也没用。
> 
> 那选项的作用是你使用ng填节点信息，它帮你生成配置，生不生成fakedns的，你现在是全自定义了，xray core读的就是你自己自定义的东西

好像是勾了才会使用任意门导入的dns？我用ps aux看命令行是勾了之后才有 `--dnsgw 127.0.0.1:10853` ，没勾的话得设置vpn dns不然就是用的系统默认dns

**Comment by chika0801** [comment]
> 勾了才会使用任意门导入的dns？我用 `ps aux | grep v2ray` 看命令行是勾了之后才有 `--dnsgw 127.0.0.1:10853` ，没勾的话得设置vpn dns不然就是用的系统默认dns

你说的参数是启用本地DNS，他问的是启用虚拟DNS另外一个参数
