### ISSUE TITLE
Failed to Build Sniffing Config with Unknown Protocol "quick" in Steal Yourself Server Config

### ISSUE THREAD

**Issue by us254** [chika0801/Xray-examples#70]
Observe the error message: "infra/conf: failed to build sniffing config > infra/conf: unknown protocol: quick."

```
"sniffing": {
  "enabled": true,
  "destOverride": [
  "http", 
  "tls",
  "quick"
   ]
}
```

Expected Behavior:
The Xray service should be able to build the sniffing configuration without any errors and start successfully with the specified protocols.

I encountered an issue while using the Xray software with the Steal Yourself server configuration where it failed to build the sniffing configuration due to an unknown protocol called "quick". 

Additional Information:

Xray version: 1.8.3
Operating System: Ubuntu 21.04
Xray configuration file: /usr/local/etc/xray/config.json.
Please note that the "quick" protocol is causing the issue, as indicated by the error message.

**Comment by chika0801** [comment]
"quic" 

no quick?

**Comment by us254** [comment]
Yes, you are correct. Thank you for bringing the typo to my attention.

**Comment by chika0801** [comment]
No thanks
