### ISSUE TITLE
xray如何设置屏蔽访问国内IP

### ISSUE THREAD

**Issue by cheneyxx** [chika0801/Xray-examples#72]

**Comment by chika0801** [comment]
路由部分用

`"domainStrategy": "IPIfNonMatch",`

```
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
```

推荐入站部分把嗅探参数加上，确保收到的请求最终是域名

```
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
```

在这示例中有


你还可以把CN IP扔到warp里，参考 https://github.com/chika0801/Xray-examples/blob/main/wireguard.md 来修改

**Comment by cheneyxx** [comment]
大佬 设置好了 抖音 美团 酷安都起作用了

我还有一个疑问 就是分享节点给朋友 他们喜欢一直用🚀代理模式全局使用app 想问一下xray能不能改配置文件让全局代理的时候无法使用微信呢 我想开了全局微信都不能用了 他们就不会继续用代理模式了吧。。

**Comment by cheneyxx** [comment]
好 我听你的 谢谢

**Comment by cheneyxx** [comment]
{
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private",
                    "geoip:netflix"
                ],
                "outboundTag": "block"
 }

如果要屏蔽netflix 是不是应该这样设置

**Comment by chika0801** [comment]
```
            {
                "type": "field",
                "domain": [
                    "geosite:netflix"
                ],
                "outboundTag": "block"
            }
```

用这个 "geosite:netflix" ，确保入站里开了域名嗅探那部分参数，路由规则用的 "domainStrategy": "IPIfNonMatch",

**Comment by cheneyxx** [comment]
谢谢 昨天把 bt 协议一起 block 了

**Comment by chika0801** [comment]
> 谢谢 昨天把 bt 协议一起 block 了

禁BT那个，我没用过，听别人说加了对现在的BT也没什么好效果。你与其禁止，不如直接告诉你共用的人叫他们留意下，或不管BT得了。

**Comment by cheneyxx** [comment]
> > 谢谢 昨天把 bt 协议一起 block 了
> 
> 禁BT那个，我没用过，听别人说加了对现在的BT也没什么好效果。你与其禁止，不如直接告诉你共用的人叫他们留意下，或不管BT得了。

好的 我也是设置了不知道生效不 我也不用bt下载
