### ISSUE TITLE
偷自己证书的配置，nginx反向代理无法获取到用户ip

### ISSUE THREAD

**Issue by xixky** [chika0801/Xray-examples#73]
emby和alist获取到用户的ip都是127.0.0.1
只需要在
```
set_real_ip_from 127.0.0.1;
```
这一句下面添加一句
```
real_ip_header proxy_protocol;
```
nginx下面的反向代理应用就可以获取到ip了

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/steal_yourself/nginx.conf

我用这个配置，nginx的日志是有访问者的IP的

**Comment by chika0801** [comment]
> nginx日记是有ip的，但是nginx代理的emby获取到的ip是127.0.0.1

懂你意思了，我是没用过 nginx代理的emby ，谢谢你的建议。
