### ISSUE TITLE
Steal_Oneself seems to use the wrong Domain

### ISSUE THREAD

**Issue by houmie** [chika0801/Xray-examples#74]
Hello Chika,

I hope you are doing well.

I was looking at your `Steal_Oneself` example

1) Shouldn't this be my own domain instead of www.lovelive-anime.jp?

```
set $website                       www.lovelive-anime.jp; # 反向代理的网站
```
[see here](https://github.com/chika0801/Xray-examples/blob/144b73e70526a000338d21a28f3a5a3d539359de/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf#L64) why does it point to www.lovelive-anime.jp?

2) Wouldn't be simpler to use Caddy instead of Nginx?

Thank you for your advice,

**Comment by chika0801** [comment]
> Shouldn't this be my own domain instead of [www.lovelive-anime.jp](http://www.lovelive-anime.jp/)?

If you have, for example, a wordpress program on your own VPS, or a network drive program, you can modify the nginx configuration yourself.

You can even use nginx's default http web pages.

It doesn't matter what content is displayed, for the experience we gained in China. Personally, I don't think the firewall (GFW) will manually access your own domain.

So this URL is just a personal hobby of mine, nothing else in particular .

**Comment by chika0801** [comment]
> Wouldn't be simpler to use Caddy instead of Nginx?

I am not going to use caddy. if you will, you can use it. Note a problem in Xray's configuration, Xver = 1 This parameter, listen 127.0.0.1:8003 ssl http2 proxy_protocol;

The nginx configuration needs to add the proxy_protocol, otherwise the access will fail.

If you don't find a proxy_protocol parameter in caddy that does the same thing, you need to set Xver = 0. As a result, Caddy's logs won't have the real IPs of the visitors to your VPS.

**Comment by houmie** [comment]
I understand. Thank you. I'm still undecided if I should use nginx or Caddy. Let's see, which one I will use at the end. :-)

So going back to your config_server.json:
```
"serverNames": [
                        "www.my_own_domain.com"
],
```

Then in nginx.conf I have to use the same domain address, correct?:
```
set $website    www.my_own_domain.com;
```

and one more thing about the ciphers:

I can see you are using:
```
ssl_ciphers             TLS13_AES_128_GCM_SHA256:TLS13_AES_256_GCM_SHA384:TLS13_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305;
```

What do you think of these instead?
```
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
```
I read somewhere that using AES is bad, as GFW can easier find us.

**Comment by chika0801** [comment]
Regarding the kind of cipher suite used in the nginx configuration, I was also searching and reading other people's blog posts that mentioned it. I can't remember the link to the blog post I was reading at the time.

The nginx configuration I'm using right now, passes the test at https://www.ssllabs.com/ssltest/ and gets an A+ . Although that score probably doesn't help much. Was just trying to get an A+ on this site test at the time.

**Comment by chika0801** [comment]
`set $website    www.my_own_domain.com;`

With this reverse proxy, you mean you have a VPS with one of your own normal websites on it. Are you trying to fill in the address of your own website here? If that's what you mean, sure.

**Comment by chika0801** [comment]
```
"serverNames": [
                        "www.my_own_domain.com"
],
```

The parameter that I'm suggesting you fill in here in your NGINX configuration is to load a copy of your own SSL certificate. This certificate contains the domain name of the application.

You take this domain name and set it to resolve correctly to the IP address of your current VPS. Then, in the REALITY configuration parameter, fill in the domain name you set.

In this way, when ordinary people visit this domain name, the content of the web page displayed will be the content of the reverse proxy website you set up. (Although I don't think anyone will really visit your URL, you can imagine that you are fine and visit your own, I don't think it has too much practical meaning)

**Comment by houmie** [comment]
Ah I understand. So I need two VPS.

VPS-1 that is just showing a decoy website with proper SSL certificate.
VPS-2 that contains the xray and nginx configurations from ```Steal_oneself``` example, which points to VPS-1.

Practically it means:

**config_server.json on VPS-2:**
```
"serverNames": [
   "www.VPS-1.com"
],
```
**Nginx.conf on VPS-2:**
```
set $website    www.VPS-1.com;
```

Is this correct? 😅 
Thanks

**Comment by houmie** [comment]
> You take this domain name and set it to resolve correctly to the IP address of your current VPS. Then, in the REALITY configuration parameter, fill in the domain name you set.

Sorry, I misunderstood earlier.  So in your example, www.example.com is pointing to the IP address of the same Xray VPS server.

```
"realitySettings": {
                    "dest": "8003",
                    "xver": 1, 
                    "serverNames": [
                        "www.example.com"
                    ],
                    "privateKey": "2KZ4uouMKgI8nR-LDJNP1_MHisCJOmKGj9jUjZLncVU", 
                    "shortIds": [
                        "6ba85179e30d4fc2"
                    ]
                }
```

Then the same Xray VPS server has the nginx configuration that has ```set $website    www.my_other_website.com;``` , which points to my other VPS that serves a normal website with SSL certificate.

Thank you. I will try this and let you know if I succeeded. :-)

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/steal_oneself/config_server.json#L38



Inside this link, I'm explaining it in a paragraph of notes.

I'll summarize my personal recommendation by saying that I registered 1 domain name, which points to my VPS, and I applied for an SSL certificate for that domain name.

This SSL certificate is loaded by the nginx configuration. At this point my recommendation is

`"serverNames": [ "www.example.com" ],`

www.example.com You replace this URL with the 1 domain you registered yourself.

You can also not do this, what I mean in the comment is that you can use any other url (I recommend that the url is not from your country, for example, I am in China and the url is not from China)

If you are using your own domain name, I think this is the best solution.

Of course, if you configure it as suggested above, you can type in your own domain name in your own browser, and the content will be the content of the website that you have reverse proxied in the nginx configuration.

**Comment by houmie** [comment]
Thank you, Chika for the clarification. 
I will try this.
Much appreciated
