### ISSUE TITLE
关于warp账户获取的命令

### ISSUE THREAD

**Issue by toyo2333** [chika0801/Xray-examples#76]
使用 warp-reg，注册warp账号

curl -sLo warp-reg https://github.com/badafans/warp-reg/releases/download/v1.0/main-linux-amd64 && chmod +x warp-reg && ./warp-reg && rm warp-reg
使用 api.zeroteam.top，获取warp账号

curl -sLo /root/warp "https://api.zeroteam.top/warp?format=xray" > /dev/null && grep -Eo --color=never '"2606:4700:[0-9a-f:]+/128"|"secretKey":"[0-9a-zA-Z\/+]+="|"reserved":\[[0-9]+(,[0-9]+){2}\]' warp && rm warp

我想问，上面两个命令是2选1还是说要先后分别执行?

**Comment by chika0801** [comment]
2选1，随便用哪一个。
