### ISSUE TITLE
大佬能否考虑用caddy2来做一个偷自己的示例？

### ISSUE THREAD

**Issue by toyo2333** [chika0801/Xray-examples#77]
因为仅仅是做反向代理的话，caddy2是否更简单？（你的那个偷自己的nginx配置看起来好复杂啊。。。）

而且caddy2签署证书和自动续期都更加简单。

放在这个场景下，是不是比Ngnix更纯粹呢？

**Comment by chika0801** [comment]
我不会caddy，推荐你去 https://github.com/lxhao61/integrated-examples 咨询。
