### ISSUE TITLE
Dest & SNI

### ISSUE THREAD

**Issue by iamtheted** [chika0801/Xray-examples#78]
Hello There,
I hope you're doing well!

I am really confused when It comes to "Dest" and "SNI" in Reality configuration.
Some people say Dest matters more than SNI. 
Which one does the GFW see? Dest or SNI? 
Can you please clarify this if It's possible? :)

I really appreciate you

**Comment by chika0801** [comment]
GFW (or your network operator) can see the IP of the server you're accessing, which is not the URL you put in the Dest section of the server configuration. It is the IP of your VPS.

Also the SNI can be seen in the request you send. This SNI is the value you put in the "serverName": "www.lovelive-anime.jp" parameter on the client side. Because this value needs to be one of your server side "serverName" list.

If you don't understand the logic, please add your question.

**Comment by iamtheted** [comment]
So the way I see It, Dest can be an IP if that IP belongs to the SNI we have set, right?

Also can you please take a look at this reply? 
https://github.com/XTLS/Xray-core/issues/2077#issuecomment-1547546962 

RPRX says "Dest" must be an actual website persuming he means TLS 1.3 and h2, right? and SNI can be anything.
Now the way I see It what RPRX says and what you say are against each other, is that right?
Or maybe I don't get what RPRX actually says because It's in Chinese and I had to translate It to English.

Please update me on this if It's possible
Thank you for your time,
I really appreciate you :)

**Comment by chika0801** [comment]
> So the way I see It, Dest can be an IP if that IP belongs to the SNI we have set, right?

Depends on your specific website, as not every website applies for an IP certificate for their IP. I don't think most small sites have IP certificates. So I think this is a special play and not recommended for the average person to try.

**Comment by chika0801** [comment]
> RPRX says "Dest" must be an actual website persuming he means TLS 1.3 and h2, right? and SNI can be anything.

He means the dest target site you're looking for, which is conditioned on TLS 1.3 h2 x25519.

**Comment by iamtheted** [comment]
> > So the way I see It, Dest can be an IP if that IP belongs to the SNI we have set, right?
> 
> Depends on your specific website, as not every website applies for an IP certificate for their IP. I don't think most small sites have IP certificates. So I think this is a special play and not recommended for the average person to try.

look I'm not sure if I explained it clearly or not

        "realitySettings": {
          "show": false,
          "dest": "IP.IP.IP.IP:443",
          "xver": 0,
          "serverNames": [
            "sub.example.com"

That's what I mean by Dest.
You said GFW only sees VPS IP & SNI so would It matter if I set an IP of the SNI in Dest just like I have put it in the code above? 
Which one has to be TLS 1.3 / h2 / x25519 ? Dest or the SNI? 

Let me explain what I have done and you tell me if It's a mistake or not.
        "realitySettings": {
          "show": false,
          "dest": "IP.IP.IP.IP:443",
          "xver": 0,
          "serverNames": [
            "sub.example.com"

I have put a TLS 1.3 / h2 / x25519 website in servername section and an IP of that website in Dest section.
It has been working okay but to be completely honest with you, I have no idea if what I have done does follow reality standards or not, is it gonna be detected in the future? This is the part I do not understand clearly.

**Comment by chika0801** [comment]
> That's what I mean by Dest.

I understand that you meant this usage in your question.

> You said GFW only sees VPS IP & SNI so would It matter if I set an IP of the SNI in Dest just like I have put it in the code above?

The firewall in your area, sees the request you sent, the IP address of your VPS, and the SNI name you filled in.

> Which one has to be TLS 1.3 / h2 / x25519 ? Dest or the SNI?

`dest` parameter here, you fill in the domain name, or IP address, and it's SSL certificate should meet these requirements.


> I have put a TLS 1.3 / h2 / x25519 website in servername section and an IP of that website in Dest section.
> It has been working okay but to be completely honest with you, I have no idea if what I have done does follow reality > standards or not, is it gonna be detected in the future? This is the part I do not understand clearly.

This is no different than if you just put example.com in the dest parameter.

Fill in some special IP (for example, 1.1.1.1) in the dest parameter is the REALITY hidden play mentioned by the author of XRAY, at this time, the value of "serverNames" on the server side is left blank.

Client "serverNames" can be filled with any URL or not.

**Comment by chika0801** [comment]
If you still have questions, just keep replying again.
