### ISSUE TITLE
Xver

### ISSUE THREAD

**Issue by iamtheted** [chika0801/Xray-examples#79]
Hello Again,
I hope you're doing great!

What is the difference between xver:0 & xver:1 ? Can you please help me understand this?
This reality configuration is so complicated even people can't use it properly let alone gfw blocking it lol

**Comment by chika0801** [comment]
If you don't use REALITY + Steal Your Own, the default value of Xver parameter, when you don't write it on the server side, is 0. If you want to write it, please use 0. If you fill in 1 or 2, it will be an error, and the client will not be able to connect successfully.

If you use to steal their own configuration form, this Xver with 1 or 2, the role is the same, the role is to pass the visitor's real IP to the back-end programme, here the back-end programme I mean nginx, nginx logs can record the IP of the access to your VPS (usually these IPs are mostly search engine spiders)
