### ISSUE TITLE
关于ssl_early_data

### ISSUE THREAD

**Issue by ahdiua** [chika0801/Xray-examples#82]
感谢高海佬的example。

请教下，在你的steal oneself里，我发现nginx配置[L45](https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf#L45)中，default server配置了ssl_early_data on，但是在真正的host里却没有ssl_early_data。请问这是由什么深意吗？

**Comment by chika0801** [comment]
给反代配置用的  `proxy_set_header Early-Data           $ssl_early_data;`

https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/steal_oneself/nginx.conf#L99

加这个只是去https://www.ssllabs.com/ssltest测试时图个好看，我也不100%确定位置加到生效没有。去这网站检测时是yes了。

**Comment by ahdiua** [comment]
原来如此，理解了，感谢
