### ISSUE TITLE
VLESS-XTLS-Vision面临主动探测时的反应应该是什么？

### ISSUE THREAD

**Issue by someonewating** [chika0801/Xray-examples#83]
您好，

我按照[https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-Vision](url) 的配置，监听了443端口，可以正常访问google，也配置了nginx。对于配置中的`dest`有点疑惑。我自己尝试执行了 `curl -v [域名]:443` 后得到了
```
Empty reply from server
Connection #0 to host [域名] left intact
curl: (52) Empty reply from server
```
我想问一下VLESS-XTLS-Vision应该有的反应是什么？为什么我 `curl -v [域名]:443` 后没有显示nginx配置文件里转发的`www.lovelive-anime.jp`的html代码？是我的理解有误吗？nginx配置文件完全和您的样例一致，server-config我也只修改了域名和证书等必要参数。

谢谢。

**Comment by chika0801** [comment]
> 配置中的dest

dest那你看文档，只填数字，意思是127.0.0.1:8001

是用的VLESS协议的回落功能，普通的访问请求传给了nginx，然后nginx那边是反代的网站。

你问题是在浏览器输入你的域名，没显示出来反代的网页？

**Comment by chika0801** [comment]
```
我自己尝试执行了 curl -v [域名]:443 后得到了

Empty reply from server
Connection #0 to host [域名] left intact
curl: (52) Empty reply from server
```
正常显示什么我也不清楚，我平时也没用这命令试过。如果用这套组合，搭完，就访问自己域名，显示出网页内容，nginx日志access.log也自己的访问记录，就是正常的。

**Comment by someonewating** [comment]
> 

您好。
原理我是明白的，但是我的现象是访问`[域名]:[xray监听端口]`，浏览器报了503错误。
按照我的理解，访问`[域名]:[xray监听端口]`应该被nginx转发到`www.lovelive-anime.jp`。但是我不确定我的理解是不是错了。

**Comment by chika0801** [comment]
你在浏览器中输入 域名 能打开网页内容不了？

**Comment by someonewating** [comment]
> 你在浏览器中输入 域名 能打开网页内容不了？

不行，只输入域名就报503，但是指定域名和端口就正常。

**Comment by chika0801** [comment]
> > 你在浏览器中输入 域名 能打开网页内容不了？
> 
> 不行，只输入域名就报503，但是指定域名和端口就正常。

那我不清楚为什么了。我用配置示例中的正常就是前面说的能显示。

你说你又没改过nginx配置。

你要我帮你看，就帖你现在的nginx和xray配置出来

你是把域名正确指向了VPS的IP的吧？ SSL证书中也是用这域名申请的吧。这些点排查下了。

**Comment by someonewating** [comment]
> > > 你在浏览器中输入 域名 能打开网页内容不了？
> > 
> > 
> > 不行，只输入域名就报503，但是指定域名和端口就正常。
> 
> 那我不清楚为什么了。我用配置示例中的正常就是前面说的能显示。
> 
> 你说你又没改过nginx配置。
> 
> 你要我帮你看，就帖你现在的nginx和xray配置出来
> 
> 你是把域名正确指向了VPS的IP的吧？ SSL证书中也是用这域名申请的吧。这些点排查下了。

谢谢。我自己再研究一下，如果还是失败再请您帮忙排查。

**Comment by chika0801** [comment]
有需要再重开这个帖子。

**Comment by someonewating** [comment]
今天研究了一下，原因是nginx跑在了docker里，监听容器内`127.0.0.1`导致没收到xray转发过来的请求。把监听的ip改为分配给容器的ip后就正常了。
另外请教一下，这个nginx转发到`www.lovelive-anime.jp`有必要换成其他的吗？还是说转发网址是什么并不重要？

**Comment by chika0801** [comment]
> 今天研究了一下，原因是nginx跑在了docker里

我从不用docker，所以我也猜不到这个原因。

> 这个nginx转发到www.lovelive-anime.jp有必要换成其他的吗？还是说转发网址是什么并不重要？

随便哪个网址，这只是个人爱好。我觉得GFW不会人工打开你网址看显示什么。所以不重要了。你不要反代在中国大陆地区不能直接访问的那些网站吧这个基本看法有吧。
