### ISSUE TITLE
WARP Plus license

### ISSUE THREAD

**Issue by hawshemi** [chika0801/Xray-examples#84]
_Hello._

I'm testing the `wireguard` function in the `xray-core` and successfully connected to it. for now, I'm routing only `openai` to WARP.

My question is: **Is there a way I could use WARP Plus by including my WARP License?**

Right now when I open https://chat.openai.com/cdn-cgi/trace, It says `warp=on` but on my other server which I used another script that can put license, it says `warp=plus`.

`config.json`:

```
{
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "port": "443",
                "network": "udp",
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:ir",
                    "geoip:private"
                ],
                "outboundTag": "block"
            },
			      {
                "type": "field",
                "domain": [
                    "geosite:openai"
                ],
                "outboundTag": "warp-IPv6"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XXX"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "security": "reality",
                "realitySettings": {
                    "dest": "www.XXX:443",
                    "serverNames": [ 
                        "www.XXX"
                    ],
                    "privateKey": "XXXX",
                    "shortIds": [
                        "" 
                    ]
                },
                "grpcSettings": {
                    "serviceName": "speedtest"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "proxySettings": {
                "tag": "wireguard"
            },
            "tag": "warp-IPv4"
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv6"
            },
            "proxySettings": {
                "tag": "wireguard"
            },
            "tag": "warp-IPv6"
        },
        {
            "protocol": "wireguard",
            "settings": {
                "secretKey": "XXX",
                "address": [
                    "172.16.0.2/32",
                    "XXX/128"
                ],
                "peers": [
                    {
                        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "allowedIPs": [
                            "0.0.0.0/0",
                            "::/0"
                        ],
                        "endpoint": "162.159.192.1:2408"
                    }
                ],
                "reserved":[XXX],
                "mtu": 1280
            },
            "tag": "wireguard"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 2,
                "connIdle": 120
            }
        }
    }
}
```
_Thanks again for your guidance._

**Comment by chika0801** [comment]
I rechecked Xray and sing-box's configuration instructions about wireguard, and I determined that Xray and sing-box should not be able to modify the WARP License. this is my personal opinion.

I checked the Warp script https://github.com/fscarmen/warp/tree/main which is popular in Chinese community I suggest you to go to this link if you have to use warp+, it has many methods. Some of the ideas are to create a virtual NIC via wgcf or warp-go and then hijack the outbound traffic. Which would be able to modify the License.

> 引用Luminous大神原话：实际测试WARP+在访问非CF的网站速度上和免费版没有差异，只有在访问CloudFlare的站点时付费版会通过Argo类似的技术通过与目标较近的数据中心前往源站，而免费版是仅限于连接地前往源站，仅此而已。

Quote from Luminous: Actual testing of WARP+ shows no difference in speed from the free version when accessing non-CF sites, only when accessing CloudFlare sites the paid version goes to the source via Argo-like technology via a datacenter closer to the target, whereas the free version is limited to connecting to the source, and that's it.

**Comment by hawshemi** [comment]
Yes. I use the script that creates a service name `WARP` and `127.0.0.1:40000`. then you can upgrade it via license to `WARP+`.
However the main problem is high CPU/RAM usage. I use these services to route to `WARP`:
```
[
  "geosite:google",
  "geosite:openai",
  "geosite:netflix",
  "geosite:spotify",
  "geosite:cloudflare",
  "geosite:meta",
  "geosite:microsoft",
  "geosite:vimeo",
  "geosite:amazon",
  "geosite:aws",
  "geosite:nvidia"
]
```
When the number of users reaches about 50, the `WARP` service will almost occupy 2Gb of RAM... I'm searching for more resource-friendly `WARP` services that can be upgraded to `WARP-Plus`.


> only when accessing CloudFlare sites 

There are a lot of Cloudflare sites...

**Comment by KoinuDayo** [comment]
You can try out this api script: ( don't delete `@` )
```
bash -c "$(curl -L https://github.com/fscarmen/warp/raw/main/api.sh)" @ 
```
Use argument `-r -f warp,json` to registe a warp account, then use `-f warp.json -l [LICENSE]` to bind your license to this account.
Use `-f warp.json -i` to get your `reserved` field.
You can find your account pubkey and private key in `warp.json` . 
If you want to change your device name, you can use `-f warp.json -n [NAME]`.

>PS:
>If you leave the Xray process running for too long, it may encounter a memory overflow issue.
>You can try outbound to [sing-box](https://github.com/SagerNet/sing-box)'s wireguard to fix it.


Here's a routing example:
sing-box:
```json5
{
    "log": {
        "level": "info",
        "timestamp": true
    },
    "inbounds": [
        {
            "type": "socks",
            "tag": "In",
            "listen": "127.0.0.1",
            "listen_port": 1024,
            "tcp_fast_open": true
        }
    ],
    "outbounds": [
        {
            "type": "wireguard",
            "tag": "WARP",
            "server": "162.159.195.1",
            "server_port": 2408,
            "local_address": [
                "172.16.0.2/32",
                "/128" 
            ],
            "private_key": "", 
            "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "reserved": , 
            "mtu": 1440
        }
```
Xray:
```json5
{

  "inbounds": [
    // Keep your original fields.
  ],
  "outbounds": [
    {
      "tag": "WARP-Sing",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 1024
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [],
        "network": "udp",
        "port": "443",
        "outboundTag": "block"
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "block",
        "domain": [
          "fill.with.the.domain.you.want.to.block"
        ]
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "block",
        "ip": [
          "fill.with.the.ip.you.want.to.block"
        ]
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "domain": [
          "fill.with.the.domain.you.want.to.direct.out(won't go to warp)"
        ]
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "ip": [
          "fill.with.the.ip.you.want.to.direct.out(won't go to warp)"
        ]
      }
    ]
  }
}

```

**Comment by chika0801** [comment]
> Yes. I use the script that creates a service name WARP and 127.0.0.1:40000.

Listen to what you mean by that. You should be using the official CLI program from cloudflare, which provides a socks 40000 port. I haven't used it for long though. I've seen other people in the Chinese community report that the problem with the official CLI program is that the memory footprint gets very high after using it for a long time.

https://github.com/ViRb3/wgcf/releases

Have you tried wgcf, a tool that uses the kernel wireguard?

For example, if your current VPS is called A and its IP quality is not good, you can additionally buy another VPS called B. This B, its IP quality is good. You can forward geosite:google/openai (e.g. using shadowsocks protocol) from A to B via Xray's configuration file.

This is also a solution idea, the bad thing is that you have to spend more money to buy VPS B. I've done it this way myself.

**Comment by hawshemi** [comment]
Yes, I used https://github.com/ViRb3/wgcf/ and generated `.conf` with Plus licence then entered them in the xray `config.json`.
Now it's using Warp Plus directly using wireguard protocol in the `xray-core`.
