### ISSUE TITLE
关于多协议共用的问题

### ISSUE THREAD

**Issue by iwoomi** [chika0801/Xray-examples#9]
大佬，我看了你的[VLESS-TCP-TLS+VMess-Websocket-TLS+Trojan-TCP-TLS](https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS)多协议共用的配置方案，该方案中[config_server.json](https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS/config_server.json)的fallback如下
![image](https://user-images.githubusercontent.com/13575500/187148454-a0e20ddd-68fc-4516-946e-572e36c08b27.png)

在[这个文档](https://xtls.github.io/document/level-1/fallbacks-with-sni.html#xray-%E9%85%8D%E7%BD%AE)中有以下描述
> 在上述配置中，每条回落到 Nginx 的配置都要分成两个。这是因为 h2 是强制 TLS 加密的 HTTP/2 连接，这有益于数据在互联网中传输的安全，但在服务器内部没有必要；而 h2c 是非加密的 HTTP/2 连接，适合该环境。然而，Nginx 不能在同一端口上同时监听 HTTP/1.1 和 h2c，为了解决这个问题，需要在回落中指定 alpn 项（是 fallbacks 而不是 xtlsSettings 里面的），以尝试匹配 TLS ALPN 协商结果。

我看你是把非h2流量从8001端口转发到nginx，而h2流量则通8004直接给了trojan，由trojan过滤出trojan流量，如果是非trojan流量则会由trojan的fallback通过8002端口转发给nginx，由于trojan一开始接收的流量就是h2的，所以它转发的也是h2的，nginx那边自然就要用h2端口来接收。

以上是我的理解，但我不明白的是，你为什么能确定trojan流量一定是h2流量呢？万一8001那边也有trojan流量呢？我是不明白内部流量的具体协议，所以想问问🤣

其实另一种方式是，你把fallback模块③去掉，那么此时无论是h2还是非h2流量，全部都会通过8001转发给trojan(trojan模块改为监听8001)，然后由trojan从其中过滤出自己的流量，其它非trojan流量由trojan的fallback流出转发到nginx，当然由于nginx需要分端口监听h2和非h2，所以trojan的fallback需要分h2和非h2两个端口转发给nginx，但现在的问题是：trojan是否也支持通过alpn参数来指定h2流量？

我目前的做法就是我上边说的，在xray的fallback里不区分h2和非h2，然后由trojan来分，实测使用没啥问题，xray的443可用，trojan可用，ws也可用，直接访问域名可正常打开网页！但你的配置也是可用的，所以我现在就不太明白， trojan流量是否一定是h2流量？xray的trojan模块的fallback是否支持alpn指定h2，从而把流量分开h2和非h2两个端口转发给nginx呢？

你看rprx大佬写的，xray fallback那边他是没有特地分个h2流量给trojan，而是全部一起给它
![image](https://user-images.githubusercontent.com/112089622/187159398-bb0ee984-86fe-4e64-8212-c6f8434476c6.png)

但他的trojan模块又没有区分h2和非h2
![image](https://user-images.githubusercontent.com/112089622/187159712-d56fcec3-aaf2-434c-a90f-5166818625e2.png)

**Comment by chika0801** [comment]
我抄官方的和加谁的（忘记了）。h2优先什么的原理也记不到了，你有兴趣还是靠你自己查吧，我没时间再回头再一次文档和更新日志。

                    {
                        "alpn": "h2",
                        "dest": "8004",
                        "xver": 1
                    }

这里写h2，不写是因为要在客户端比如N上指定勾选才通，你这里写了，客户端那儿不用指定（怕你的客户不懂）

我想了下当时在调试时大概是发现的这原因

**Comment by iwoomi** [comment]
好的，谢谢

**Comment by chika0801** [comment]
> 好的，谢谢

我又回忆了次当时调试这配置，想起来了

https://github.com/XTLS/Xray-examples/blob/e01c18039c5b663b89aeab4395bec71b4f19461f/VLESS-TCP-XTLS-WHATEVER/config_server.json#L46

你看这配置的alpn只写了1。1

我的配置没写这个参数，不写时默认值你去查文档，xray那个官方配置可能是当时还在更新，后来更新时alpn这儿我默认都是写出来的，后来不写也用默认的h2在前1。1在后。

当时写这配置我也研究了半天，是这原因改成现在的样子。

**Comment by iwoomi** [comment]
> > 好的，谢谢
> 
> 想起来了
> 
> https://github.com/XTLS/Xray-examples/blob/e01c18039c5b663b89aeab4395bec71b4f19461f/VLESS-TCP-XTLS-WHATEVER/config_server.json#L46
> 
> 你看这alpn只写了1.1
> 
> xray版本更新时alpn不写的默认值现在应该是h2在前,1.1在后，历史更新过程我记不清了，最后发展到nginx接时也要写h2和http 2个也是这原因。
> 
> 我的配置没写这个参数，用的默认值，我当时调试了下，这样弄，客户端比如v2rayn不用钩1.1还是http2。

哦哦，其实，我试了客户端无论勾不勾，勾哪个都不影响使用🤣
